import type { ContentPack, DailyCard } from '../types'

/**
 * Denní karty pro jádro IVF cyklu.
 *
 * Tohle je motor celé platformy. Karta se vybírá přesnou shodou na den,
 * takže uživatelka ve stimulaci nebo v čekání na HCG dostane každé ráno
 * text napsaný právě pro ten den — ne obecný článek o fázi.
 *
 * Zdrojem popisu vývoje embrya je běžná embryologická praxe; časování se mezi
 * klinikami liší a nikde z toho nevyvozujeme, jak dopadne konkrétní cyklus.
 */

// --------------------------------------------------------------- stimulace ---

const stimulation: DailyCard[] = [
  {
    id: 'ck-stim-0',
    phases: ['stimulation'],
    day: 0,
    headline: 'První injekce. Nejtěžší je ta dnešní.',
    body: 'Dnes začíná stimulace. Většina žen se první injekce bojí víc než všech ostatních dohromady — a po třetím dni ji píchá při telefonování. Ruce se můžou třást, to je v pořádku.',
    whatsHappening: [
      'Léky začínají povzbuzovat růst folikulů ve vaječnících.',
      'Zatím nic necítíte. To je normální, ne špatné znamení.',
      'Místo vpichu může být na chvíli začervenalé.',
    ],
    task: 'Připravte si na lednici jedno stálé místo jen pro léky. Ať je nemusíte každý večer hledat.',
    reflection: 'Čeho se na dnešku bojíte nejvíc — jehly, nebo toho, co bude za dva týdny?',
    tip: 'Injekci si dejte každý den ve stejnou dobu. Nastavte si budík se jménem, které vás nevyděsí uprostřed schůzky.',
  },
  {
    id: 'ck-stim-1',
    phases: ['stimulation'],
    day: 1,
    headline: 'Druhý den. Tělo si zvyká.',
    body: 'Zatím se nic dramatického neděje a to je dobře. Folikuly potřebují několik dní, než se vůbec dají změřit.',
    whatsHappening: [
      'Ve vaječnících začíná růst víc folikulů najednou než v přirozeném cyklu.',
      'Můžete se cítit mírně unavená.',
      'Po vpichu se občas udělá modřina — nic to neznamená.',
    ],
    task: 'Vypijte dnes o jednu sklenici vody víc než včera.',
    reflection: 'Komu jste zatím řekla, že do toho jdete? A komu ne — a proč?',
    tip: 'Modřinám pomůže střídat strany a před vpichem místo na chvíli zahřát dlaní.',
  },
  {
    id: 'ck-stim-2',
    phases: ['stimulation'],
    day: 2,
    headline: 'Třetí den. Rutina se rodí rychleji, než čekáte.',
    body: 'Zvládla jste tři večery po sobě. To, co v pondělí vypadalo nemožně, je ve středu obyčejná věc — a přesně tak to většinou zůstane.',
    whatsHappening: [
      'Folikuly rostou, zatím měří jen pár milimetrů.',
      'Estradiol pomalu stoupá.',
      'Nálada může být lehce rozkolísaná.',
    ],
    task: 'Napište si do poznámek jednu otázku, kterou chcete položit na první kontrole.',
    reflection: 'Co vám dnes pomohlo víc, než jste čekala?',
  },
  {
    id: 'ck-stim-3',
    phases: ['stimulation'],
    day: 3,
    headline: 'Blíží se první monitoring.',
    body: 'Kolem čtvrtého až pátého dne bývá první ultrazvuk. Uvidí se, jak vaječníky reagují, a podle toho se může upravit dávka.',
    whatsHappening: [
      'Lékař změří počet a velikost folikulů.',
      'Často se zároveň odebírá krev na estradiol.',
      'Dávka se může změnit — to není chyba, tak to má být.',
    ],
    task: 'Na kontrolu si vezměte něco k pití a svačinu. Čekárny na klinikách bývají dlouhé.',
    reflection: 'Čeho se na zítřejším ultrazvuku bojíte a co byste nejradši slyšela?',
    tip: 'Zapište si čísla folikulů rovnou v ordinaci. Za týden si je nebudete pamatovat a budou se vám hodit.',
  },
  {
    id: 'ck-stim-4',
    phases: ['stimulation'],
    day: 4,
    headline: 'Čísla ještě nic neříkají.',
    body: 'Jestli jste dnes byla na monitoringu, nejspíš jste slyšela počty a milimetry. Na tomhle místě cyklu se z nich nedá vyčíst skoro nic — folikuly rostou různým tempem a některé se ještě přidají.',
    whatsHappening: [
      'Folikuly obvykle rostou zhruba o 1–2 mm denně.',
      'Menší folikuly mohou dohnat ty větší.',
      'Břicho může začít být citlivější.',
    ],
    task: 'Odpusťte si dnes jednu věc, kterou byste normálně musela udělat.',
    reflection: 'Srovnáváte se s někým? S kým, a pomáhá vám to?',
    tip: 'Nesrovnávejte svá čísla s ženami na internetu. Jiný protokol, jiný věk, jiná diagnóza — jiný výsledek.',
  },
  {
    id: 'ck-stim-5',
    phases: ['stimulation'],
    day: 5,
    headline: 'Vaječníky pracují naplno.',
    body: 'Kolem šestého dne bývá cítit tlak nebo těžkost v podbřišku. Vaječníky, které normálně vypěstují jeden folikul, jich teď mají několik — a zvětšují se.',
    whatsHappening: [
      'Tlak nebo pobolívání v podbřišku je běžné.',
      'Kalhoty můžou být těsnější.',
      'Estradiol výrazně stoupá.',
    ],
    task: 'Vyměňte dnes cokoliv upnutého za něco volného. Vážně to pomůže.',
    reflection: 'Jak se vám daří odpočívat — a co vám v tom brání?',
    tip: 'Prudké otáčení a skákání teď vynechte. Zvětšené vaječníky jsou citlivější na náhlý pohyb.',
    callDoctorIf: [
      'Bolest je náhlá, prudká a jednostranná.',
      'Máte teplotu nad 38 °C.',
      'Zvracíte a nemůžete udržet tekutiny.',
    ],
  },
  {
    id: 'ck-stim-6',
    phases: ['stimulation'],
    day: 6,
    headline: 'Sedmý den. Půlka je za vámi.',
    body: 'Většina stimulací trvá zhruba deset až dvanáct dní. Jste tedy někde v polovině — a to je zároveň místo, kde bývá nejmíň sil a nejvíc netrpělivosti.',
    whatsHappening: [
      'Folikuly se blíží velikostem, které rozhodují o načasování odběru.',
      'Můžete být plačtivá nebo podrážděná. Je to hormony, ne vaše slabost.',
      'Spánek bývá horší.',
    ],
    task: 'Napište partnerovi nebo kamarádce jednu větu o tom, jak vám opravdu je.',
    reflection: 'Co byste dnes potřebovala slyšet?',
  },
  {
    id: 'ck-stim-7',
    phases: ['stimulation'],
    day: 7,
    headline: 'Blíží se rozhodování o termínu odběru.',
    body: 'V téhle fázi se monitoringy zhušťují. Klinika hlídá, kdy je většina vedoucích folikulů dost velká — a podle toho určí čas dokončovací injekce.',
    whatsHappening: [
      'Kontroly můžou být teď obden nebo denně.',
      'Sliznice dělohy se zároveň připravuje.',
      'Nadýmání se může zhoršit.',
    ],
    task: 'Zařiďte si, aby vás den odběru někdo odvezl. Po anestezii nesmíte řídit.',
    reflection: 'Kdo vás v den odběru doprovodí — a víte, že se na to můžete spolehnout?',
    tip: 'Domluvte si v práci volno s rezervou. Termín odběru se často upřesní až den dva předem.',
  },
  {
    id: 'ck-stim-8',
    phases: ['stimulation'],
    day: 8,
    headline: 'Načasování je teď důležitější než všechno ostatní.',
    body: 'Dokončovací (trigger) injekce se píchá v přesně určenou hodinu, obvykle 34 až 36 hodin před odběrem. Tady se nedá improvizovat — vajíčka dozrávají podle hodin.',
    whatsHappening: [
      'Vedoucí folikuly se blíží cílové velikosti.',
      'Klinika vám sdělí přesný čas dokončovací injekce.',
      'Tlak v podbřišku bývá nejvýraznější právě teď.',
    ],
    task: 'Až dostanete čas triggeru, nastavte si dva budíky. Na dvou různých zařízeních.',
    reflection: 'Co vám pomáhá zůstat v klidu, když nemůžete nic ovlivnit?',
    tip: 'Čas triggeru si nechte poslat písemně nebo si ho v ordinaci přečtěte nahlas zpátky.',
  },
  {
    id: 'ck-stim-9',
    phases: ['stimulation'],
    day: 9,
    headline: 'Poslední dny stimulace.',
    body: 'Jste na konci nejnáročnější části cyklu. Tělo je unavené, břicho nafouklé a hlava plná čísel. Za pár dní bude tahle část za vámi.',
    whatsHappening: [
      'Folikuly dorůstají do cílové velikosti.',
      'Můžete se cítit vyčerpaná i po celonočním spánku.',
      'Chuť k jídlu bývá rozhozená.',
    ],
    task: 'Připravte si tašku na odběr: doklady, kartičku pojišťovny, volné oblečení, ponožky.',
    reflection: 'Co si o sobě po těchhle deseti dnech myslíte?',
    callDoctorIf: [
      'Obvod břicha rychle roste.',
      'Přibrala jste za den víc než kilogram.',
      'Hůř se vám dýchá nebo močíte výrazně méně.',
    ],
  },
  {
    id: 'ck-stim-10',
    phases: ['stimulation'],
    day: 10,
    headline: 'Skoro tam.',
    body: 'Většina protokolů se pohybuje kolem deseti až dvanácti dnů. Jestli vám klinika zatím nedala termín, není to špatné znamení — jen folikuly potřebují ještě den dva.',
    whatsHappening: [
      'Delší stimulace neznamená horší výsledek.',
      'Poslední monitoring rozhodne o termínu.',
      'Únava vrcholí.',
    ],
    task: 'Domluvte si na den po odběru, že nebudete dělat vůbec nic.',
    reflection: 'Za co si dnes můžete poděkovat?',
  },
  {
    id: 'ck-stim-11',
    phases: ['stimulation'],
    day: 11,
    headline: 'Dokončovací injekce mění všechno.',
    body: 'Trigger spustí poslední dozrání vajíček. Od jeho podání běží hodiny — proto se odběr plánuje na minuty přesně.',
    whatsHappening: [
      'Po triggeru se stimulační léky obvykle už nepíchají.',
      'Před odběrem se nesmí jíst ani pít — čas vám určí klinika.',
      'Můžete být nervózní a zároveň se ulevit, že to končí.',
    ],
    task: 'Sundejte si šperky, nalakované nehty a nalíčení nechte na jindy — usnadníte to anesteziologovi.',
    reflection: 'Až si zítra lehnete na sál, co si budete chtít připomenout?',
    tip: 'Naposledy si zkontrolujte čas příchodu na kliniku. Ne z paměti — z papíru nebo zprávy.',
  },
  {
    id: 'ck-stim-12',
    phases: ['stimulation'],
    day: 12,
    headline: 'Poslední noc před odběrem.',
    body: 'Zítra se to, co jste dva týdny živila injekcemi, konečně ukáže. Dnes už nemůžete udělat nic navíc — a to je svým způsobem úleva.',
    whatsHappening: [
      'Od určené hodiny nejíst ani nepít.',
      'Spánek nejspíš nebude nejlepší. To zvládnete.',
      'Ráno se dostavíte podle pokynů kliniky.',
    ],
    task: 'Nachystejte si všechno k posteli, ať ráno jen vstanete a jdete.',
    reflection: 'Co jste za posledních dvanáct dní zvládla, o čem jste si myslela, že nezvládnete?',
  },
]

// ----------------------------------------------------------------- odběr ---

const retrieval: DailyCard[] = [
  {
    id: 'ck-retr-0',
    phases: ['retrieval'],
    day: 0,
    headline: 'Dnes je den odběru.',
    body: 'Zákrok obvykle trvá kolem patnácti minut a probíhá v krátké anestezii. Většina žen je do několika hodin doma. Číslo, které dnes uslyšíte, je počet získaných vajíček — ne počet embryí.',
    whatsHappening: [
      'Po probuzení můžete být rozlepená a rozklepaná. To přejde.',
      'Bývá slabé špinění a křeče podobné menstruačním.',
      'Vajíčka putují rovnou do embryologické laboratoře.',
    ],
    task: 'Dnes už jen ležte. Vážně nic jiného.',
    reflection: 'Co jste cítila v okamžiku, kdy vám řekli počet vajíček?',
    tip: 'Pijte po douškách a raději minerálku než čistou vodu. Pomáhá to proti nadýmání.',
    callDoctorIf: [
      'Krvácíte silně, víc než při menstruaci.',
      'Máte prudkou bolest, kterou neutlumí předepsaná analgetika.',
      'Máte teplotu nad 38 °C.',
      'Točí se vám hlava nebo omdléváte.',
    ],
  },
  {
    id: 'ck-retr-1',
    phases: ['fertilization'],
    day: 1,
    headline: 'Dnes volá embryologie.',
    body: 'Včera se vajíčka setkala se spermiemi. Dnes laboratoř zjistí, kolik z nich se oplodnilo. Číslo bývá nižší než počet odebraných vajíček — ne všechna jsou zralá a ne všechna se oplodní.',
    whatsHappening: [
      'Oplodnění se hodnotí podle přítomnosti dvou prvojader.',
      'Telefonát obvykle přijde dopoledne.',
      'Břicho může být pořád citlivé a nafouklé.',
    ],
    task: 'Než zavolají, napište si, co se chcete zeptat. Po telefonátu si to nevybavíte.',
    reflection: 'Jak jste noc zvládla — a čeho jste se bála nejvíc?',
    tip: 'Až budou volat, poproste je, ať vám čísla zopakují. Nikdo se nezlobí.',
    callDoctorIf: [
      'Obvod břicha rychle roste nebo jste přes noc výrazně přibrala.',
      'Hůř se vám dýchá.',
      'Močíte výrazně méně než obvykle.',
    ],
  },
  {
    id: 'ck-retr-2',
    phases: ['embryo_culture'],
    day: 2,
    headline: 'Embrya se začínají dělit.',
    body: 'Druhý den po odběru mívají embrya zhruba dvě až čtyři buňky. Laboratoř sleduje, jak pravidelně se dělí, ale zásadní rozhodnutí padají až později.',
    whatsHappening: [
      'Ne všechna oplodněná vajíčka se dělí dál — to je běžné.',
      'Klinika vám nemusí volat každý den. Ticho neznamená špatnou zprávu.',
      'Vy mezitím jen odpočíváte.',
    ],
    task: 'Zaměstnejte si dnes hlavu něčím, co nemá s IVF nic společného.',
    reflection: 'Co vám pomáhá, když nemůžete nic ovlivnit?',
  },
  {
    id: 'ck-retr-3',
    phases: ['embryo_culture'],
    day: 3,
    headline: 'Třetí den. Osm buněk je ideál, ne podmínka.',
    body: 'Kolem třetího dne mívá embryo šest až osm buněk. Některé kliniky přenášejí právě teď, jiné čekají do pátého dne — obojí je běžná praxe a záleží na vašem konkrétním případu.',
    whatsHappening: [
      'Embryo přebírá řízení vlastního vývoje.',
      'Část embryí se v tuhle chvíli zastaví. Není to nic, co byste ovlivnila.',
      'Klinika vám řekne, jestli se transferuje dnes, nebo se čeká.',
    ],
    task: 'Zeptejte se, podle čeho se vaše klinika rozhoduje mezi třetím a pátým dnem.',
    reflection: 'Věříte tomu, co se právě děje? A co by vám v tom pomohlo?',
  },
  {
    id: 'ck-retr-4',
    phases: ['embryo_culture'],
    day: 4,
    headline: 'Nejtišší den celého cyklu.',
    body: 'Čtvrtý den se embryo mění v moruly — kompaktní shluk, ve kterém se buňky přestávají dát spočítat. Většina laboratoří proto čtvrtý den nehlásí nic. Ticho je normální.',
    whatsHappening: [
      'Buňky se spojují a připravují na další krok.',
      'Většina klinik dnes nevolá.',
      'Vy nemůžete udělat vůbec nic. To je zároveň úleva.',
    ],
    task: 'Jděte na půl hodiny ven bez telefonu.',
    reflection: 'Co si dnes o sobě říkáte — a řekla byste to tak i kamarádce?',
  },
  {
    id: 'ck-retr-5',
    phases: ['embryo_culture'],
    day: 5,
    headline: 'Blastocysta.',
    body: 'Pátý den může embryo dosáhnout stadia blastocysty — má dutinu a dvě rozlišené skupiny buněk, ze kterých vznikne miminko a placenta. Některá embrya to zvládnou až šestý den, a to není horší.',
    whatsHappening: [
      'Hodnocení bývá kombinace čísla a dvou písmen (například 4AB).',
      'Písmena popisují vzhled, ne osud. I hůř hodnocená embrya se uhnízdí.',
      'Dnes se často rozhoduje o transferu nebo zamražení.',
    ],
    task: 'Až uslyšíte hodnocení, zapište si ho přesně. Slovo od slova.',
    reflection: 'Jaké to je, vědět, že rozhodnutí padlo bez vás?',
    tip: 'Zeptejte se, co konkrétně u vás znamená doporučení transferovat nebo zamrazit. Odpověď se liší případ od případu.',
  },
  {
    id: 'ck-retr-6',
    phases: ['embryo_culture'],
    day: 6,
    headline: 'Šestý den — poslední, kdo dobíhá, doběhne.',
    body: 'Část embryí dosáhne stadia blastocysty až šestý den. Zpomalený vývoj neznamená, že embryo nemá šanci.',
    whatsHappening: [
      'Laboratoř dnes uzavírá kultivaci.',
      'Zamražují se embrya, která dosáhla potřebného stadia.',
      'Dozvíte se konečný počet.',
    ],
    task: 'Ať už dnešek přinesl cokoliv, zapište si to do deníku. Za rok to budete chtít vědět.',
    reflection: 'Co byste dnes řekla sama sobě před třemi měsíci?',
  },
]

// --------------------------------------------------------------- transfer ---

const transfer: DailyCard[] = [
  {
    id: 'ck-transfer-0',
    phases: ['transfer'],
    day: 0,
    headline: 'Dnes je transfer.',
    body: 'Zákrok trvá pár minut, obvykle bez anestezie, a připomíná spíš odběr cytologie než operaci. Nejnepříjemnější na tom bývá plný močový měchýř, ne samotný přenos.',
    whatsHappening: [
      'Embryolog vám může embryo ukázat na monitoru.',
      'Po transferu se obvykle chvíli poležíte, pak jdete domů.',
      'Slabé špinění nebo křeče po zavedení katétru jsou běžné.',
    ],
    task: 'Vyfoťte si snímek embrya, pokud ho dostanete. Za pár let bude mít cenu.',
    reflection: 'Chcete si dnešek zapamatovat. Co z něj?',
    tip: 'Embryo z dělohy nevypadne. Ani když si kýchnete, ani když půjdete na záchod, ani když se postavíte.',
  },
]

// ---------------------------------------------------- čekání na beta HCG ---

const twoWeekWait: DailyCard[] = [
  {
    id: 'ck-tww-1',
    phases: ['two_week_wait'],
    day: 1,
    headline: 'Vaše embryo se právě líhne.',
    body: 'První den po transferu se blastocysta uvolňuje z obalu, který ji dosud chránil. Aby se mohla uhnízdit, musí se z něj nejdřív dostat ven.',
    whatsHappening: [
      'Embryo se zbavuje obalu (zona pellucida).',
      'Zatím není nijak spojené s vaším tělem.',
      'Žádné příznaky teď nemůžou nic znamenat — je příliš brzo.',
    ],
    task: 'Naplánujte si na příštích deset dní tři konkrétní věci, na které se můžete těšit.',
    reflection: 'Jak chcete tyhle dva týdny prožít — a co to znamená prakticky?',
    tip: 'Ležení v posteli šance nezvyšuje. Běžný pohyb ano — pro vaši hlavu.',
  },
  {
    id: 'ck-tww-2',
    phases: ['two_week_wait'],
    day: 2,
    headline: 'Embryo hledá místo.',
    body: 'Druhý den se uvolněná blastocysta pohybuje v dutině děložní a dotýká se sliznice. Zatím jen zkoumá terén.',
    whatsHappening: [
      'Embryo je stále volné, přichycení teprve přijde.',
      'Progesteron, který užíváte, připravuje sliznici.',
      'Nafouklé břicho po stimulaci ještě může přetrvávat.',
    ],
    task: 'Sledujte dnes něco, u čeho se zasmějete. Cokoliv.',
    reflection: 'Kolikrát jste dnes zkontrolovala své tělo, jestli něco necítíte?',
    tip: 'Progesteron sám o sobě dělá napětí v prsou, únavu i nadýmání. Proto z příznaků teď nic nevyčtete.',
  },
  {
    id: 'ck-tww-3',
    phases: ['two_week_wait'],
    day: 3,
    headline: 'Začíná přichycení.',
    body: 'Třetí den se embryo začíná přichytávat ke sliznici. Je to první skutečný kontakt mezi ním a vámi — a probíhá naprosto potichu.',
    whatsHappening: [
      'Embryo přilne k děložní sliznici.',
      'Nic z toho není cítit. Opravdu nic.',
      'Test by byl dnes negativní i při naprosto ideálním průběhu.',
    ],
    task: 'Schovejte si domácí testy někam, kam se nedá jen tak sáhnout.',
    reflection: 'Čeho se bojíte víc — negativního testu, nebo dalšího čekání?',
  },
  {
    id: 'ck-tww-4',
    phases: ['two_week_wait'],
    day: 4,
    headline: 'Zahnizďování začíná.',
    body: 'Čtvrtý den se embryo začíná zanořovat do sliznice. Tenhle proces trvá několik dní a je nejdůležitější věcí, která se právě teď ve vašem těle děje.',
    whatsHappening: [
      'Buňky budoucí placenty pronikají do sliznice.',
      'Někdy se objeví slabé narůžovělé špinění. Může, ale nemusí.',
      'Slabé píchání v podbřišku je běžné — a neznamená nic.',
    ],
    task: 'Napište si jednu větu do deníku. Jen jednu.',
    reflection: 'Co byste chtěla, aby o dnešku věděl někdo za deset let?',
    callDoctorIf: [
      'Krvácíte jasně červeně a víc než při menstruaci.',
      'Máte prudkou bolest v podbřišku.',
      'Máte teplotu nad 38 °C.',
    ],
  },
  {
    id: 'ck-tww-5',
    phases: ['two_week_wait'],
    day: 5,
    headline: 'Možná právě teď vzniká první HCG.',
    body: 'Pátý den může embryo, které se uhnízdilo, začít tvořit hormon HCG. Množství je zatím tak malé, že ho nezachytí žádný test.',
    whatsHappening: [
      'Zahnizďování pokračuje.',
      'První molekuly HCG se dostávají do krve.',
      'Domácí test by byl stále negativní.',
    ],
    task: 'Udělejte si dnes večer patnáct minut jen pro sebe. Bez telefonu.',
    reflection: 'Komu jste zatím neřekla, jak vám je?',
    tip: 'Pokud vás láká testovat, dejte si podmínku: ne dřív než v den, kdy to má smysl. Ušetříte si zbytečnou ránu.',
  },
  {
    id: 'ck-tww-6',
    phases: ['two_week_wait'],
    day: 6,
    headline: 'Šestý den. Nejhorší je, že nic neuvidíte.',
    body: 'Uhnízdění se obvykle dokončuje mezi šestým a desátým dnem po transferu blastocysty. Probíhá bez jediného příznaku, který byste mohla zaznamenat.',
    whatsHappening: [
      'Embryo se zanořuje hlouběji do sliznice.',
      'HCG pomalu stoupá, ale zatím pod hranicí detekce.',
      'Cokoliv cítíte, může být od progesteronu.',
    ],
    task: 'Zavolejte někomu, kdo o vaší léčbě neví. Mluvte o čemkoliv jiném.',
    reflection: 'Co dnes bylo lehčí, než jste čekala?',
  },
  {
    id: 'ck-tww-7',
    phases: ['two_week_wait'],
    day: 7,
    headline: 'Sedmý den. Půlka čekání je za vámi.',
    body: 'Zvládla jste týden. Zbývá zhruba stejně dlouhá doba do odběru krve — a tahle druhá půlka bývá subjektivně delší.',
    whatsHappening: [
      'Pokud se embryo uhnízdilo, HCG stoupá.',
      'Test doma by mohl vyjít slabě pozitivní, ale často ještě ne.',
      'Únava a napětí v prsou nic nedokazují — obojí dělá i progesteron.',
    ],
    task: 'Zapište si, jak jste na tom s náladou. Uvidíte v tom pak vlnu, ne jeden špatný den.',
    reflection: 'Kdyby se vás dnes někdo zeptal, jak to zvládáte, co byste opravdu odpověděla?',
  },
  {
    id: 'ck-tww-8',
    phases: ['two_week_wait'],
    day: 8,
    headline: 'Osmý den. Testovat, nebo netestovat.',
    body: 'Od tohohle dne může citlivější domácí test zachytit HCG — ale taky nemusí, i když je všechno v pořádku. Negativní test dnes nic neuzavírá.',
    whatsHappening: [
      'HCG se při zdárném vývoji přibližně zdvojnásobuje každých 48 až 72 hodin.',
      'Zbytek dokončovací injekce už bývá z těla pryč, ale ne u každé.',
      'Slabá čárka je čárka. Žádná čárka není konec.',
    ],
    task: 'Rozhodněte se dnes, jestli budete testovat doma. A to rozhodnutí dodržte.',
    reflection: 'Chcete to vědět dřív, nebo jistě?',
    tip: 'Když se rozhodnete testovat, udělejte to ráno z první moči a s někým, kdo je vám nablízku.',
  },
  {
    id: 'ck-tww-9',
    phases: ['two_week_wait'],
    day: 9,
    headline: 'Devátý den. Hlava pracuje víc než tělo.',
    body: 'V týhle fázi většina žen popisuje, že se přistihují při analyzování každého pocitu. Je to naprosto pochopitelné — a zároveň to nic nezjistí.',
    whatsHappening: [
      'Při uhnízdění HCG dál stoupá.',
      'Příznaky raného těhotenství a příznaky před menstruací se nedají rozlišit.',
      'Špinění může, ale nemusí být.',
    ],
    task: 'Napište si seznam všeho, co v tomhle čekání zvládáte. Bude delší, než čekáte.',
    reflection: 'Co si o sobě po těchhle devíti dnech myslíte?',
  },
  {
    id: 'ck-tww-10',
    phases: ['two_week_wait'],
    day: 10,
    headline: 'Desátý den. Test už bývá spolehlivější.',
    body: 'Kolem desátého dne po transferu blastocysty bývá domácí test u probíhajícího těhotenství obvykle pozitivní. Rozhodující je ale vždycky odběr krve.',
    whatsHappening: [
      'HCG bývá dost vysoké na záchyt běžným testem.',
      'Slabá čárka může znamenat brzké stadium, ne slabé těhotenství.',
      'Odběr krve se obvykle plánuje mezi 10. a 14. dnem.',
    ],
    task: 'Ověřte si, kdy přesně máte jít na odběr — a kdy se dozvíte výsledek.',
    reflection: 'Jak si chcete výsledek nechat sdělit? A kdo u toho má být?',
  },
  {
    id: 'ck-tww-11',
    phases: ['two_week_wait'],
    day: 11,
    headline: 'Jedenáctý den. Blíží se konec čekání.',
    body: 'Ať to dopadne jakkoliv, tahle část končí. Čekání je svým způsobem těžší než jistota — i než ta špatná.',
    whatsHappening: [
      'HCG při zdárném vývoji dál stoupá.',
      'Progesteron se obvykle užívá dál až do výsledku.',
      'Špinění před odběrem nemusí znamenat konec.',
    ],
    task: 'Naplánujte si na den výsledku něco měkkého. Ne pracovní schůzku.',
    reflection: 'Co budete potřebovat, ať to dopadne jakkoliv?',
    tip: 'Progesteron nevysazujte sama od sebe, ani když začnete špinit. Vždycky se nejdřív zeptejte kliniky.',
  },
  {
    id: 'ck-tww-12',
    phases: ['two_week_wait'],
    day: 12,
    headline: 'Dvanáctý den. Skoro tam.',
    body: 'Odběr krve bývá mezi desátým a čtrnáctým dnem. Číslo, které z něj vyjde, se nedá porovnávat s ničím cizím — rozptyl u zdravých těhotenství je obrovský.',
    whatsHappening: [
      'Beta HCG se z krve stanoví během několika hodin.',
      'Často se odběr za dva dny opakuje kvůli dynamice.',
      'Jedna hodnota sama o sobě říká málo.',
    ],
    task: 'Připravte si dvě otázky pro chvíli, kdy vám budou výsledek sdělovat.',
    reflection: 'Čeho se na zítřku bojíte nejvíc?',
  },
  {
    id: 'ck-tww-13',
    phases: ['two_week_wait'],
    day: 13,
    headline: 'Zítra nebo dnes. Konec čekání.',
    body: 'Dva týdny, které trvaly déle než celý zbytek roku. Ať už bude číslo jakékoliv, tuhle část jste zvládla.',
    whatsHappening: [
      'Na odběr nemusíte být nalačno, pokud vám neřekli jinak.',
      'Výsledek bývá tentýž den.',
      'Je normální mít strach i naději zároveň.',
    ],
    task: 'Domluvte se s někým, komu zavoláte jako prvnímu — ať to dopadne jakkoliv.',
    reflection: 'Co si o těchhle čtrnácti dnech chcete zapamatovat?',
  },
  {
    id: 'ck-tww-14',
    phases: ['two_week_wait'],
    day: 14,
    headline: 'Den odběru.',
    body: 'Dnes se to dozvíte. Ať přijde jakékoliv číslo, budete potřebovat čas ho vstřebat — i to dobré.',
    whatsHappening: [
      'Beta HCG se stanoví z krve.',
      'Při pozitivním výsledku se odběr obvykle za 48 hodin opakuje.',
      'Při negativním výsledku vám klinika řekne, kdy vysadit léky.',
    ],
    task: 'Ať výsledek dopadne jakkoliv, dnes už nic neplánujte.',
    reflection: 'Co potřebujete slyšet právě teď?',
    callDoctorIf: [
      'Krvácíte silně a máte prudkou bolest.',
      'Máte bolest v rameni spolu s bolestí břicha.',
      'Točí se vám hlava nebo omdléváte.',
    ],
  },
]

// ------------------------------------------------------ po pozitivním testu ---

const betaPositive: DailyCard[] = [
  {
    id: 'ck-beta-0',
    phases: ['beta_positive'],
    dayRange: [0, 1],
    headline: 'Dvě čárky. A hned s nimi nová vlna otázek.',
    body: 'Je normální, že se místo čisté radosti dostaví opatrnost a strach. Po tom, čím jste prošla, si tělo i hlava nedovolí uvěřit hned.',
    whatsHappening: [
      'Odběr se obvykle za 48 hodin opakuje kvůli dynamice hodnoty.',
      'Progesteron a další podpora se užívá dál podle pokynů kliniky.',
      'Radost i strach zároveň je běžná kombinace.',
    ],
    task: 'Zapište si dnešní datum a hodnotu do deníku. Za rok to budete chtít vidět.',
    reflection: 'Dovolila jste si to už říct nahlas?',
  },
  {
    id: 'ck-beta-1',
    phases: ['beta_positive'],
    dayRange: [2, 4],
    headline: 'Sleduje se dynamika, ne jedno číslo.',
    body: 'V rané fázi je důležitější, jak hodnota roste, než jak je vysoká. Orientačně se očekává přibližně zdvojnásobení za 48 až 72 hodin, ale odchylky nejsou vzácné.',
    whatsHappening: [
      'Druhý odběr ukáže trend.',
      'Rozptyl hodnot mezi zdravými těhotenstvími je obrovský.',
      'Srovnávat své číslo s cizím nedává smysl.',
    ],
    task: 'Přestaňte hledat tabulky hodnot na internetu. Vážně.',
    reflection: 'Co by vám teď pomohlo víc než další číslo?',
  },
  {
    id: 'ck-beta-2',
    phases: ['beta_positive'],
    dayRange: [5, 12],
    headline: 'Čekání na první ultrazvuk.',
    body: 'První ultrazvuk bývá kolem šestého až sedmého týdne. Do té doby zase čekáte — a tohle čekání je jiné než to předchozí, ale ne snazší.',
    whatsHappening: [
      'Hledá se gestační váček, později žloutkový váček a embryo.',
      'Srdeční akce bývá viditelná zhruba od 6. týdne.',
      'Slabé špinění v tomhle období není vzácné, ale vždycky ho hlaste.',
    ],
    task: 'Zapište si do kalendáře termín ultrazvuku, ať na něj máte co odpočítávat.',
    reflection: 'Jak se změnil váš strach za poslední týden?',
    callDoctorIf: [
      'Krvácíte jasně červeně nebo se špinění zhoršuje.',
      'Máte prudkou nebo jednostrannou bolest břicha.',
      'Máte bolest v rameni, točí se vám hlava nebo omdléváte.',
    ],
  },
  {
    id: 'ck-beta-3',
    phases: ['beta_positive'],
    dayRange: [13, 30],
    headline: 'Těhotenství po IVF má vlastní pravidla.',
    body: 'Vy víte přesně, který den vzniklo. Víte, kolik to stálo úsilí. A právě proto se hůř uvolňuje — to není vaše chyba, to je logika toho, čím jste prošla.',
    whatsHappening: [
      'Podpora luteální fáze obvykle pokračuje několik týdnů.',
      'Nevolnosti a únava se mohou objevit kolem šestého týdne.',
      'Péči postupně přebírá váš gynekolog.',
    ],
    task: 'Zeptejte se na klinice, do kdy máte užívat podporu a kdy přejít ke svému gynekologovi.',
    reflection: 'Co byste potřebovala, abyste si dovolila se radovat?',
  },
]

export const pack: ContentPack = {
  dailyCards: [
    ...stimulation,
    ...retrieval,
    ...transfer,
    ...twoWeekWait,
    ...betaPositive,
  ],
}
