import type { ContentPack, Product } from '../types'

/**
 * Marketplace.
 *
 * Řazení podle relevance k aktuální fázi, ne podle toho, kdo zaplatí za reklamu.
 * Každá položka má `whyNow` — vysvětlení, proč se hodí právě teď. Bez toho
 * by to byl jen katalog.
 *
 * Ceny jsou orientační v Kč a slouží k odhadu rozpočtu, ne jako nabídka.
 */

const products: Product[] = [
  // --- Příprava a IVF ------------------------------------------------------
  {
    id: 'mp-folat',
    name: 'Kyselina listová s aktivním folátem',
    category: 'Doplňky stravy',
    whyNow:
      'Doporučuje se začít užívat ideálně tři měsíce před početím. Konkrétní přípravek a dávku vám doporučí lékař — tady jde jen o orientaci, co se běžně užívá.',
    priceFrom: 290,
    phases: ['thinking', 'preparing_body', 'trying_naturally', 'ivf_prep', 'early_pregnancy'],
    rating: 4.8,
    reviews: 412,
    vendor: 'Lékárna',
    kind: 'product',
    hero: 'sage',
  },
  {
    id: 'mp-vitamin-d',
    name: 'Vitamin D3 s vitaminem K2',
    category: 'Doplňky stravy',
    whyNow:
      'V našich zeměpisných šířkách bývá vitamin D nízký hlavně v zimě. Před léčbou se často kontroluje a doplňuje — dávkování určuje lékař podle naměřené hodnoty.',
    priceFrom: 220,
    phases: ['preparing_body', 'ivf_prep', 'stimulation', 'pregnancy'],
    rating: 4.7,
    reviews: 298,
    vendor: 'Lékárna',
    kind: 'product',
    hero: 'champagne',
  },
  {
    id: 'mp-ovulacni-testy',
    name: 'Ovulační testy — balení 20 ks',
    category: 'Testy',
    whyNow:
      'Když sledujete plodné dny, vyplatí se testovat několik dní v řadě. Velké balení vyjde levněji než kupovat po kusech každý cyklus.',
    priceFrom: 340,
    phases: ['trying_naturally', 'preparing_body'],
    excludeModifiers: [],
    rating: 4.5,
    reviews: 631,
    vendor: 'Lékárna',
    kind: 'product',
    hero: 'linen',
  },
  {
    id: 'mp-chladici-pouzdro',
    name: 'Chladicí pouzdro na léky',
    category: 'Pomůcky',
    whyNow:
      'Většina léků na stimulaci se skladuje v chladu. Pouzdro řeší cestu z lékárny, dovolenou i den, kdy si musíte píchnout mimo domov.',
    priceFrom: 690,
    phases: ['ivf_prep', 'stimulation'],
    rating: 4.9,
    reviews: 147,
    vendor: 'Specializovaný prodejce',
    kind: 'product',
    hero: 'sky',
  },
  {
    id: 'mp-organizer-leky',
    name: 'Organizér na medikaci s denním rozvrhem',
    category: 'Pomůcky',
    whyNow:
      'Ve stimulaci se často kombinuje víc léků v různý čas. Organizér snižuje riziko, že se v tom v návalu ztratíte.',
    priceFrom: 350,
    phases: ['stimulation', 'ivf_prep', 'transfer', 'two_week_wait'],
    rating: 4.6,
    reviews: 92,
    vendor: 'Lékárna',
    kind: 'product',
    hero: 'sand',
  },
  {
    id: 'mp-tehotenske-testy',
    name: 'Těhotenské testy s vysokou citlivostí',
    category: 'Testy',
    whyNow:
      'Když se rozhodnete testovat doma, citlivější test zachytí HCG dřív. Rozhodující je ale vždycky odběr krve na klinice.',
    priceFrom: 180,
    phases: ['two_week_wait', 'trying_naturally', 'iui'],
    rating: 4.4,
    reviews: 803,
    vendor: 'Lékárna',
    kind: 'product',
    hero: 'pearl',
  },
  {
    id: 'mp-nahrivaci-polstarek',
    name: 'Nahřívací polštářek s pohankovou náplní',
    category: 'Pomůcky',
    whyNow:
      'Po odběru vajíček bývá břicho citlivé a nadmuté. Mírné teplo na záda a podbřišek uleví — na břicho po transferu ale pozor, ptejte se na klinice.',
    priceFrom: 450,
    phases: ['retrieval', 'embryo_culture', 'loss_miscarriage'],
    rating: 4.7,
    reviews: 211,
    vendor: 'Specializovaný prodejce',
    kind: 'product',
    hero: 'blush',
  },

  // --- Těhotenství ---------------------------------------------------------
  {
    id: 'mp-tehotensky-polstar',
    name: 'Těhotenský polštář ve tvaru U',
    category: 'Spánek',
    whyNow:
      'Od druhého trimestru se doporučuje spát na boku a rostoucí bříško potřebuje podepřít. Polštář se pak hodí i při kojení.',
    priceFrom: 1290,
    phases: ['pregnancy', 'high_risk_pregnancy', 'birth_prep', 'postpartum'],
    gestWeeks: [16, 42],
    rating: 4.8,
    reviews: 524,
    vendor: 'Specializovaný prodejce',
    kind: 'product',
    hero: 'blush',
  },
  {
    id: 'mp-krem-strie',
    name: 'Tělový olej na strie',
    category: 'Kosmetika',
    whyNow:
      'Sklon ke striím je hlavně věc genetiky, promazávání ale pomáhá proti napínání a svědění rostoucí kůže.',
    priceFrom: 390,
    phases: ['pregnancy', 'birth_prep'],
    rating: 4.5,
    reviews: 367,
    vendor: 'Drogerie',
    kind: 'product',
    hero: 'dawn',
  },
  {
    id: 'mp-tlakomer',
    name: 'Domácí tlakoměr na paži',
    category: 'Monitorování',
    whyNow:
      'Při rizikovém těhotenství nebo sledování tlaku vám lékař může doporučit měřit doma. Naměřené hodnoty si můžete rovnou zapisovat do zdravotního přehledu v aplikaci.',
    priceFrom: 990,
    phases: ['high_risk_pregnancy', 'pregnancy', 'hospitalization'],
    modifiers: ['high_risk', 'preeclampsia'],
    rating: 4.7,
    reviews: 189,
    vendor: 'Zdravotnické potřeby',
    kind: 'product',
    hero: 'sky',
  },

  // --- Porod ---------------------------------------------------------------
  {
    id: 'mp-taska-porodnice',
    name: 'Připravená taška do porodnice',
    category: 'Porod',
    whyNow:
      'Od 36. týdne by měla být taška hotová a u dveří. Předchystaná varianta ušetří rozhodování ve chvíli, kdy na to nebude čas.',
    priceFrom: 1490,
    phases: ['birth_prep', 'pregnancy'],
    gestWeeks: [32, 42],
    rating: 4.6,
    reviews: 143,
    vendor: 'Specializovaný prodejce',
    kind: 'product',
    hero: 'linen',
  },
  {
    id: 'mp-sitovane-kalhotky',
    name: 'Jednorázové síťované kalhotky',
    category: 'Po porodu',
    whyNow:
      'První dny po porodu jsou porodnické vložky velké a běžné prádlo je nepohodlné. Tyhle kalhotky jsou nejpraktičtější věc, na kterou se často zapomene.',
    priceFrom: 240,
    phases: ['birth', 'postpartum', 'preterm_birth'],
    rating: 4.9,
    reviews: 678,
    vendor: 'Drogerie',
    kind: 'product',
    hero: 'pearl',
  },
  {
    id: 'mp-pas-po-cisari',
    name: 'Břišní pás po císařském řezu',
    category: 'Po porodu',
    whyNow:
      'Po císaři pomáhá pás při vstávání a chůzi v prvních dnech. Kdy a jak dlouho ho nosit, se zeptejte na oddělení nebo fyzioterapeuta.',
    priceFrom: 890,
    phases: ['birth', 'postpartum'],
    modifiers: ['csection'],
    rating: 4.7,
    reviews: 254,
    vendor: 'Zdravotnické potřeby',
    kind: 'product',
    hero: 'sand',
  },
  {
    id: 'mp-chladici-vlozky',
    name: 'Chladivé gelové vložky na hráz',
    category: 'Po porodu',
    whyNow:
      'Po přirozeném porodu, obzvlášť po nástřihu nebo poranění, chlazení výrazně uleví v prvních dnech.',
    priceFrom: 320,
    phases: ['birth', 'postpartum'],
    modifiers: ['vaginal_birth'],
    rating: 4.8,
    reviews: 312,
    vendor: 'Lékárna',
    kind: 'product',
    hero: 'sage',
  },

  // --- Kojení a krmení -----------------------------------------------------
  {
    id: 'mp-odsavacka',
    name: 'Elektrická odsávačka mléka — dvoufázová',
    category: 'Kojení',
    whyNow:
      'Hodí se při rozjezdu laktace, při nalití prsou, u nedonošeného miminka i před návratem do práce. Dvoufázová napodobuje sání miminka.',
    priceFrom: 3490,
    phases: ['postpartum', 'nicu', 'coming_home', 'baby_first_year'],
    modifiers: ['breastfeeding', 'pumping', 'preterm'],
    rating: 4.7,
    reviews: 891,
    vendor: 'Specializovaný prodejce',
    kind: 'product',
    hero: 'pearl',
  },
  {
    id: 'mp-vlozky-podprsenka',
    name: 'Prací vložky do podprsenky',
    category: 'Kojení',
    whyNow:
      'V prvních týdnech mléko často samo odtéká. Prací vložky vyjdou levněji než jednorázové a jsou šetrnější k pokožce.',
    priceFrom: 290,
    phases: ['postpartum', 'baby_first_year'],
    modifiers: ['breastfeeding', 'pumping'],
    rating: 4.6,
    reviews: 405,
    vendor: 'Specializovaný prodejce',
    kind: 'product',
    hero: 'linen',
  },
  {
    id: 'mp-lanolin',
    name: 'Čistý lanolin na bradavky',
    category: 'Kojení',
    whyNow:
      'Při ragádách uleví a nemusí se před kojením smývat. Pokud ale bolest neustupuje, důvod bývá v přisátí — na to je potřeba laktační poradkyně.',
    priceFrom: 250,
    phases: ['postpartum', 'nicu', 'coming_home'],
    modifiers: ['breastfeeding'],
    rating: 4.8,
    reviews: 522,
    vendor: 'Lékárna',
    kind: 'product',
    hero: 'dawn',
  },
  {
    id: 'mp-sterilizator',
    name: 'Parní sterilizátor lahví',
    category: 'Krmení',
    whyNow:
      'Když krmíte lahví nebo odstříkáváte, sterilizátor ušetří spoustu času oproti vyvařování v hrnci.',
    priceFrom: 1690,
    phases: ['postpartum', 'coming_home', 'baby_first_year', 'nicu'],
    modifiers: ['formula_feeding', 'combination_feeding', 'pumping'],
    rating: 4.7,
    reviews: 376,
    vendor: 'Specializovaný prodejce',
    kind: 'product',
    hero: 'sky',
  },
  {
    id: 'mp-lahvicky',
    name: 'Kojenecké lahvičky s pomalým průtokem',
    category: 'Krmení',
    whyNow:
      'Pomalý průtok umožňuje miminku pít vlastním tempem — to je zásadní hlavně u nedonošených dětí a při kombinovaném krmení.',
    priceFrom: 490,
    phases: ['nicu', 'coming_home', 'postpartum', 'baby_first_year'],
    modifiers: ['formula_feeding', 'combination_feeding', 'preterm'],
    rating: 4.6,
    reviews: 448,
    vendor: 'Specializovaný prodejce',
    kind: 'product',
    hero: 'pearl',
  },

  // --- Nedonošené miminko --------------------------------------------------
  {
    id: 'mp-klokankovaci-triko',
    name: 'Klokánkovací tričko',
    category: 'Nedonošené',
    whyNow:
      'Klokánkování je jedna z mála věcí, které pro miminko na JIP můžete udělat jenom vy. Tričko drží miminko bezpečně a máte volné ruce.',
    priceFrom: 890,
    phases: ['nicu', 'preterm_birth', 'coming_home'],
    modifiers: ['preterm', 'nicu_stay'],
    rating: 4.9,
    reviews: 118,
    vendor: 'Specializovaný prodejce',
    kind: 'product',
    hero: 'blush',
  },
  {
    id: 'mp-obleceni-nedonosene',
    name: 'Oblečení pro nedonošené (velikost 44–50)',
    category: 'Nedonošené',
    whyNow:
      'Běžné novorozenecké velikosti jsou pro miminko po předčasném porodu obrovské. Tahle velikost se v běžných obchodech shání těžko.',
    priceFrom: 390,
    phases: ['nicu', 'coming_home', 'preterm_birth'],
    modifiers: ['preterm'],
    rating: 4.8,
    reviews: 96,
    vendor: 'Specializovaný prodejce',
    kind: 'product',
    hero: 'sage',
  },
  {
    id: 'mp-monitor-dechu',
    name: 'Monitor dechu pod matraci',
    category: 'Monitorování',
    whyNow:
      'Po návratu domů z JIP chybí zvuk monitorů, na které jste si zvykla — a spánek je najednou plný kontrolování. Monitor mnoha rodičům pomůže usnout. Nenahrazuje zásady bezpečného spánku.',
    priceFrom: 2490,
    phases: ['coming_home', 'postpartum', 'baby_first_year'],
    modifiers: ['preterm', 'nicu_stay'],
    rating: 4.5,
    reviews: 289,
    vendor: 'Specializovaný prodejce',
    kind: 'product',
    hero: 'sky',
  },

  // --- Miminko -------------------------------------------------------------
  {
    id: 'mp-zavinovacka',
    name: 'Zavinovačka na suchý zip',
    category: 'Spánek',
    whyNow:
      'Zavinutí tlumí úlekový reflex a mnoha novorozencům pomáhá spát klidněji. Se zipem to zvládnete i ve tři ráno a se zavřenýma očima.',
    priceFrom: 590,
    phases: ['postpartum', 'coming_home', 'baby_first_year'],
    babyWeeks: [0, 14],
    rating: 4.7,
    reviews: 634,
    vendor: 'Specializovaný prodejce',
    kind: 'product',
    hero: 'linen',
  },
  {
    id: 'mp-nositko',
    name: 'Ergonomické nosítko',
    category: 'Nošení',
    whyNow:
      'Nošení uklidňuje miminko a vám nechá volné ruce. Ergonomické znamená, že nožičky jsou v pozici „M“ a záda podepřená.',
    priceFrom: 2290,
    phases: ['coming_home', 'baby_first_year', 'postpartum', 'toddler'],
    rating: 4.8,
    reviews: 715,
    vendor: 'Specializovaný prodejce',
    kind: 'product',
    hero: 'sand',
  },
  {
    id: 'mp-autosedacka',
    name: 'Autosedačka skupiny 0+ proti směru jízdy',
    category: 'Cestování',
    whyNow:
      'Bez autosedačky vás z porodnice nepustí domů. Pořiďte ji s předstihem a nechte si ukázat správné upoutání.',
    priceFrom: 3990,
    phases: ['birth_prep', 'pregnancy', 'birth', 'coming_home'],
    gestWeeks: [30, 42],
    rating: 4.8,
    reviews: 502,
    vendor: 'Specializovaný prodejce',
    kind: 'product',
    hero: 'sky',
  },
  {
    id: 'mp-teplomer',
    name: 'Bezdotykový teploměr',
    category: 'Zdraví dítěte',
    whyNow:
      'Teplotu budete měřit častěji, než čekáte. Bezdotykový nevzbudí spící miminko — u novorozenců ale platí, že jakákoliv teplota patří k lékaři.',
    priceFrom: 890,
    phases: ['coming_home', 'baby_first_year', 'postpartum', 'toddler'],
    rating: 4.5,
    reviews: 421,
    vendor: 'Lékárna',
    kind: 'product',
    hero: 'pearl',
  },
  {
    id: 'mp-odsavac-nosu',
    name: 'Nosní odsávačka',
    category: 'Zdraví dítěte',
    whyNow:
      'Miminko neumí smrkat a ucpaný nos mu brání v pití i spánku. První rýma přijde dřív, než si stihnete něco pořídit.',
    priceFrom: 450,
    phases: ['baby_first_year', 'coming_home', 'toddler'],
    rating: 4.6,
    reviews: 388,
    vendor: 'Lékárna',
    kind: 'product',
    hero: 'sage',
  },
  {
    id: 'mp-prikrmy-set',
    name: 'Startovací sada na příkrmy',
    category: 'Příkrmy',
    whyNow:
      'Kolem šestého měsíce (u nedonošených podle korigovaného věku) se začíná s příkrmy. Silikonové misky a lžičky přežijí házení na zem.',
    priceFrom: 690,
    phases: ['baby_first_year', 'toddler'],
    babyWeeks: [20, 60],
    rating: 4.6,
    reviews: 267,
    vendor: 'Specializovaný prodejce',
    kind: 'product',
    hero: 'dawn',
  },
]

const services: Product[] = [
  {
    id: 'mp-laktacni-poradkyne',
    name: 'Laktační poradkyně — návštěva doma',
    category: 'Odborná pomoc',
    whyNow:
      'Když kojení bolí, miminko nepřibírá nebo se nedaří přisátí, jedna návštěva odbornice často vyřeší to, co týdny čtení na internetu nespraví.',
    priceFrom: 1500,
    phases: ['postpartum', 'coming_home', 'nicu', 'baby_first_year'],
    modifiers: ['breastfeeding', 'combination_feeding'],
    rating: 4.9,
    reviews: 178,
    vendor: 'Certifikované poradkyně (IBCLC)',
    kind: 'service',
    hero: 'blush',
  },
  {
    id: 'mp-psychoterapie-neplodnost',
    name: 'Psychoterapie se zaměřením na neplodnost a ztrátu',
    category: 'Odborná pomoc',
    whyNow:
      'Léčba neplodnosti i ztráta jsou psychicky náročné a mluvit o tom s někým, kdo tomu rozumí, není slabost. Vyhledat pomoc má smysl kdykoliv, nejen když je nejhůř.',
    priceFrom: 1200,
    phases: [
      'diagnostics',
      'repeated_failure',
      'loss_miscarriage',
      'loss_missed',
      'loss_biochemical',
      'loss_ectopic',
      'waiting_next_attempt',
      'postpartum',
    ],
    rating: 4.9,
    reviews: 134,
    vendor: 'Ověření terapeuti',
    kind: 'service',
    hero: 'sage',
  },
  {
    id: 'mp-fyzioterapie-panevni-dno',
    name: 'Fyzioterapie pánevního dna',
    category: 'Odborná pomoc',
    whyNow:
      'Po porodu (přirozeném i císařem) se vyplatí nechat pánevní dno a případnou diastázu posoudit odborníkem, ne cvičit naslepo podle videí.',
    priceFrom: 900,
    phases: ['postpartum', 'baby_first_year', 'coming_home'],
    rating: 4.8,
    reviews: 156,
    vendor: 'Ověření fyzioterapeuti',
    kind: 'service',
    hero: 'sand',
  },
  {
    id: 'mp-predporodni-kurz',
    name: 'Předporodní kurz',
    category: 'Kurzy',
    whyNow:
      'Nejlepší je absolvovat ho kolem 30.–34. týdne. Naučíte se dýchání, úlevové polohy a hlavně budete vědět, co vás čeká.',
    priceFrom: 2500,
    phases: ['pregnancy', 'birth_prep'],
    gestWeeks: [26, 38],
    rating: 4.7,
    reviews: 203,
    vendor: 'Porodní asistentky',
    kind: 'service',
    hero: 'linen',
  },
  {
    id: 'mp-kurz-prvni-pomoc',
    name: 'Kurz první pomoci u dětí',
    category: 'Kurzy',
    whyNow:
      'Dušení, horečnaté křeče, pád — situace, ve kterých se rozhoduje v sekundách. Kurz absolvujte radši před tím, než ho budete potřebovat.',
    priceFrom: 1200,
    phases: ['birth_prep', 'coming_home', 'baby_first_year', 'toddler'],
    rating: 4.9,
    reviews: 241,
    vendor: 'Ověření lektoři',
    kind: 'service',
    hero: 'sky',
  },
  {
    id: 'mp-dula',
    name: 'Dula — doprovod k porodu',
    category: 'Odborná pomoc',
    whyNow:
      'Dula není zdravotník, ale nepřetržitá podpora u porodu i po něm. Domlouvá se obvykle několik měsíců předem.',
    priceFrom: 6000,
    phases: ['pregnancy', 'birth_prep'],
    gestWeeks: [20, 40],
    rating: 4.8,
    reviews: 89,
    vendor: 'Ověřené duly',
    kind: 'service',
    hero: 'dawn',
  },
  {
    id: 'mp-spankova-poradkyne',
    name: 'Spánková poradkyně',
    category: 'Odborná pomoc',
    whyNow:
      'Když se spánek rozpadne a vy jste na dně, poradkyně pomůže nastavit režim s ohledem na věk miminka — u nedonošených podle korigovaného věku.',
    priceFrom: 2000,
    phases: ['baby_first_year', 'toddler', 'coming_home'],
    babyWeeks: [8, 104],
    rating: 4.6,
    reviews: 112,
    vendor: 'Ověřené poradkyně',
    kind: 'service',
    hero: 'pearl',
  },
  {
    id: 'mp-genetick-konzultace',
    name: 'Genetická konzultace',
    category: 'Odborná pomoc',
    whyNow:
      'Po opakovaných neúspěších nebo ztrátách může mít smysl probrat genetiku s odborníkem. Doporučení k vyšetření vám dá váš lékař.',
    priceFrom: 0,
    phases: ['repeated_failure', 'genetic_testing', 'loss_missed', 'loss_miscarriage'],
    rating: 4.7,
    reviews: 67,
    vendor: 'Genetická pracoviště',
    kind: 'service',
    hero: 'sky',
  },
]

export const pack: ContentPack = {
  products: [...products, ...services],
}
