import type { ContentPack, GlossaryTerm } from '../types'

/**
 * Velký IVF slovník.
 *
 * Doplňuje pojmy, které v knihovně chyběly — hlavně laboratorní zkratky ze
 * zpráv, názvy protokolů, doplňkové metody a pojmy z genetiky a dárcovství.
 * Pravidlo je stejné jako všude: žádná zkratka bez vysvětlení a u metod
 * se slabými důkazy se to říká nahlas.
 */

const glossary: GlossaryTerm[] = [
  // --- Základní pojmy a metody -------------------------------------------
  {
    term: 'IVF',
    aliases: ['in vitro fertilizace', 'mimotělní oplodnění', 'umělé oplodnění'],
    short: 'Oplození vajíčka spermií mimo tělo, v laboratoři; vzniklé embryo se pak přenáší do dělohy.',
    long: 'Zahrnuje stimulaci vaječníků, odběr vajíček, oplození v laboratoři, kultivaci embryí a přenos. Neznamená automaticky ICSI — způsob oplození volí embryolog podle vzorku a podle předchozích cyklů. IVF neodstraňuje příčinu neplodnosti, obchází ji. Co je vhodné právě u vás, patří k rozhovoru s vaší klinikou.',
    topics: ['klinika', 'embryologie'],
  },
  {
    term: 'Asistovaná reprodukce',
    aliases: ['ART', 'metody asistované reprodukce'],
    short: 'Souhrnný název pro postupy, které pomáhají k otěhotnění mimo běžný přirozený průběh.',
    long: 'Patří sem inseminace, IVF s ICSI i bez něj, práce s darovanými buňkami, kryokonzervace a genetické testování embryí. Nejde o jednu léčbu, ale o soubor postupů, které se skládají podle konkrétní diagnózy. Podmínky úhrady, počty hrazených cyklů i věkové hranice jsou dané předpisy — zeptat se na ně hned na začátku šetří peníze i nervy.',
    topics: ['klinika', 'finance'],
  },
  {
    term: 'IVF cyklus',
    aliases: ['léčebný cyklus', 'cyklus IVF'],
    short: 'Jeden léčebný cyklus od stimulace až po využití všech embryí, která z něj vznikla.',
    long: 'Z jednoho cyklu může vzniknout víc embryí a s nimi i víc přenosů — čerstvý transfer a následné kryotransfery ze stejné zásoby. Proto se „cyklus" a „transfer" nedají zaměňovat a stejná léčba vypadá v číslech jinak podle toho, co se počítá. Když někde čtete úspěšnost, zjistěte si, jestli je uvedená na cyklus, na odběr, nebo na transfer.',
    topics: ['klinika', 'vysledky', 'finance'],
  },
  {
    term: 'Konvenční IVF',
    aliases: ['cIVF', 'klasické IVF', 'IVF bez ICSI'],
    short: 'Oplození, při kterém se vajíčko a spermie nechají v laboratoři setkat samy, bez injekce spermie.',
    long: 'Do misky s vajíčkem se přidá připravená suspenze spermií a k oplození dojde přirozenou cestou, jen mimo tělo. Volí se, když je vzorek po zpracování dostatečný; při výraznějším mužském faktoru nebo po předchozím selhání oplození bývá zvažováno ICSI. Není to slabší varianta — je to jiná odpověď na jinou situaci. O způsobu oplození rozhoduje embryolog společně s lékařem.',
    topics: ['embryologie', 'partner'],
  },
  {
    term: 'IMSI',
    aliases: ['injekce morfologicky vybrané spermie'],
    short: 'Varianta ICSI, při které embryolog vybírá spermii při mnohonásobně vyšším zvětšení.',
    long: 'Vyšší zvětšení dovolí posoudit jemné detaily hlavičky spermie, které při běžném ICSI vidět nejsou. Metoda je časově náročná a důkazy o tom, že by vedla k vyšší šanci na těhotenství, jsou zatím nejednoznačné. Bývá zvažována po opakovaném neúspěchu nebo při určitých nálezech ve spermiogramu; nejde o postup vhodný pro každý pár. Ptejte se, co konkrétně by se u vás výběrem změnilo.',
    topics: ['embryologie', 'partner'],
  },
  {
    term: 'MACS',
    aliases: ['magnetická separace spermií', 'anexin V'],
    short: 'Metoda přípravy spermií, která má oddělit ty s časnými známkami zániku buňky.',
    long: 'Vzorek projde kolonkou s magnetickými částicemi navázanými na anexin V, který se váže na poškozenou buněčnou membránu. Cílem je nechat pro oplození spermie ostatní. Data o vlivu na těhotenství a na živě narozené dítě jsou zatím omezená, proto se metoda řadí mezi doplňkové, ne standardní. Bývá zvažována například při vyšší fragmentaci DNA spermií — proberte se svou klinikou, jestli to má ve vaší situaci smysl.',
    topics: ['embryologie', 'partner'],
  },
  {
    term: 'Příprava spermií',
    aliases: ['swim-up', 'gradientová separace', 'zpracování vzorku'],
    short: 'Laboratorní zpracování ejakulátu, které oddělí pohyblivé spermie od zbytku vzorku.',
    long: 'Nejčastěji se používá průchod hustotním gradientem nebo technika swim-up, při které spermie samy vyplavou do čistého média. Odstraní se semenná plazma, buňky a nepohyblivé spermie. Stejný krok předchází inseminaci i oplození v laboratoři. Výsledek přípravy je jedním z podkladů pro rozhodnutí mezi konvenčním IVF a ICSI.',
    topics: ['embryologie', 'partner'],
  },
  {
    term: 'Time-lapse',
    aliases: ['EmbryoScope', 'časosběrné snímání', 'time-lapse inkubátor'],
    short: 'Inkubátor s kamerou, který embrya snímá průběžně, aniž by se musela vyndávat ven.',
    long: 'Embryolog tak vidí celý průběh dělení včetně okamžiků, které se při jedné denní kontrole pod mikroskopem minou. Jistou výhodou je stabilnější prostředí, protože embrya nemusí opouštět inkubátor. Jestli samotné hodnocení ze snímků vede k vyšší šanci na těhotenství, zatím jednoznačně prokázané není. Bývá nabízen jako příplatková služba — je namístě se zeptat, co za tu cenu dostanete.',
    topics: ['embryologie', 'finance'],
  },
  {
    term: 'Embryolog',
    short: 'Odborník, který v laboratoři pracuje s vajíčky, spermiemi a embryi.',
    long: 'Posuzuje zralost vajíček, provádí oplození, sleduje vývoj embryí, připravuje je k přenosu a zamrazuje je. Je to obvykle člověk, který o vašich embryích ví nejvíc, a na většině pracovišť je možné si s ním promluvit. Neurčuje léčbu — ta patří ošetřujícímu lékaři.',
    topics: ['embryologie', 'klinika'],
  },

  // --- Stimulace a protokoly ---------------------------------------------
  {
    term: 'Stimulace',
    aliases: ['ovariální stimulace', 'hormonální stimulace'],
    short: 'Podávání hormonů, po kterých dozraje víc folikulů najednou místo jediného.',
    long: 'V přirozeném cyklu dozraje obvykle jedno vajíčko a ostatní folikuly zaniknou. Stimulace dá šanci i jim, aby se z jednoho odběru získalo víc vajíček. Trvá zpravidla deset až čtrnáct dní a průběžně se kontroluje ultrazvukem a odběry krve. Dávky i délka se během ní upravují podle toho, jak vaječníky reagují — změna plánu není chyba.',
    topics: ['stimulace', 'leky'],
  },
  {
    term: 'Gonadotropiny',
    aliases: ['rekombinantní FSH', 'hMG', 'stimulační injekce'],
    short: 'Injekční léky s hormony FSH a LH, které během stimulace pohánějí růst folikulů.',
    long: 'Nahrazují nebo posilují signál, který by jinak vysílal podvěsek mozkový. Existují v rekombinantní i močové podobě a liší se poměrem účinných látek. Aplikují se obvykle podkožně, každý den zhruba ve stejnou dobu. Konkrétní přípravek i dávku určuje výhradně lékař.',
    topics: ['leky', 'stimulace', 'hormony'],
  },
  {
    term: 'GnRH antagonista',
    aliases: ['antagonista', 'cetrorelix', 'ganirelix'],
    short: 'Lék, který během stimulace brání předčasné ovulaci.',
    long: 'Blokuje vyplavení vlastního LH, takže folikuly nepraskne dřív, než se stihne odběr. Nasazuje se obvykle až v průběhu stimulace, když folikuly dosáhnou určité velikosti. Účinek nastupuje rychle a po vysazení stejně rychle odezní. V protokolu s antagonistou lze použít agonistický trigger, který snižuje riziko těžkého OHSS.',
    topics: ['leky', 'stimulace'],
  },
  {
    term: 'GnRH agonista',
    aliases: ['agonista', 'triptorelin', 'buserelin'],
    short: 'Lék, který nejprve vlastní hormony vyplaví a při delším podávání je naopak utlumí.',
    long: 'Tenhle dvojí účinek se využívá dvěma způsoby: delší podávání tlumí cyklus před stimulací, jednorázová dávka slouží jako trigger. Proto se stejná látka objevuje v úplně jiných částech léčby a snadno to mate. Přechodné návaly nebo bolest hlavy při tlumení jsou očekávaný účinek, ne komplikace. Který protokol je pro vás vhodný, rozhoduje lékař podle vaší situace.',
    topics: ['leky', 'stimulace', 'hormony'],
  },
  {
    term: 'Stimulační protokol',
    aliases: ['protokol', 'krátký protokol', 'plán stimulace'],
    short: 'Plán, který určuje, jaké léky, v jakých dávkách a kdy přesně budete v cyklu užívat.',
    long: 'Protokoly se liší hlavně tím, čím se brání předčasné ovulaci, a tím, kdy se s léky začíná. Volba vychází z ovariální rezervy, věku, diagnózy a z toho, jak jste reagovala v předchozích cyklech. Žádný protokol není univerzálně nejlepší a jeho změna mezi cykly je běžná úprava, ne přiznání chyby. Nechte si plán napsat na papír včetně časů aplikace.',
    topics: ['stimulace', 'leky', 'klinika'],
  },
  {
    term: 'Přirozený cyklus IVF',
    aliases: ['IVF bez stimulace', 'minimální stimulace', 'mini IVF'],
    short: 'IVF, ve kterém se odebírá vajíčko dozrálé ve vlastním cyklu, bez plné stimulace.',
    long: 'Vede se buď hormonálně velmi šetrně, nebo zcela bez gonadotropinů. Znamená méně léků a nižší náklady na jeden cyklus, ale obvykle také jedno vajíčko a vyšší pravděpodobnost, že cyklus skončí bez transferu. Bývá zvažován u velmi nízké ovariální rezervy nebo tam, kde stimulace není vhodná. Není to jemnější varianta pro každou — je to jiná úvaha o poměru zátěže a výtěžku.',
    topics: ['stimulace', 'klinika'],
  },
  {
    term: 'Duostim',
    aliases: ['dvojitá stimulace'],
    short: 'Dvě stimulace a dva odběry vajíček v rámci jediného menstruačního cyklu.',
    long: 'Druhá stimulace začíná krátce po prvním odběru, tedy v luteální fázi. Cílem je získat víc vajíček za kratší dobu, typicky tam, kde záleží na čase nebo je vajíček velmi málo. Embrya se zamrazují a transfer se odkládá do některého z dalších cyklů. Dostupná data jsou zatím omezená a postup nepatří mezi rutinní; o jeho vhodnosti rozhoduje lékař.',
    topics: ['stimulace', 'klinika'],
  },
  {
    term: 'Freeze-all',
    aliases: ['segmentovaný cyklus', 'elektivní kryocyklus', 'zamrazení všech embryí'],
    short: 'Postup, kdy se všechna embrya zamrazí a transfer se odloží do dalšího cyklu.',
    long: 'Volí se hlavně při riziku OHSS, při vyšší hladině progesteronu na konci stimulace, při plánovaném genetickém testování nebo když sliznice v daném cyklu není vhodná. Neznamená to, že je něco v nepořádku s embryi. Pro tělo bývá klidnější, protože přenos proběhne mimo hormonální zátěž stimulace. Rozhodnutí je individuální a patří vaší klinice.',
    topics: ['embryologie', 'transfer', 'klinika'],
  },
  {
    term: 'Slabá odpověď na stimulaci',
    aliases: ['poor responder', 'nízká ovariální odpověď'],
    short: 'Situace, kdy na stimulaci dozraje výrazně méně folikulů, než se čekalo.',
    long: 'Posuzuje se z počtu získaných vajíček, z ovariální rezervy a z průběhu předchozích cyklů. Není to selhání ženy ani chyba v aplikaci léků — nejčastěji jde prostě o počet vajíček, který ve vaječnících v danou chvíli je. Někdy pomůže změna protokolu nebo dávek, jindy je smysluplnější změnit celý plán léčby. Co je slabá odpověď právě u vás, patří k rozhovoru s lékařem.',
    topics: ['stimulace', 'vysledky', 'psychika'],
  },
  {
    term: 'Analgosedace',
    aliases: ['sedace u punkce', 'krátkodobé uspání'],
    short: 'Krátké uspání s tlumením bolesti, ve kterém obvykle probíhá odběr vajíček.',
    long: 'Není to plná celková anestezie s dýchací trubicí, ale spánek na několik desítek minut. Předchází jí lačnění podle pokynů kliniky a po ní ten den nesmíte řídit ani rozhodovat o důležitých věcech. Útlum a mírná nevolnost během několika hodin odezní. Přesná pravidla lačnění a doprovodu vám dá vaše klinika.',
    topics: ['klinika', 'sebepece'],
  },

  // --- Odběr a vajíčka ----------------------------------------------------
  {
    term: 'OPU',
    aliases: ['ovum pick-up', 'odběr oocytů', 'punkce folikulů'],
    short: 'Zkratka pro odběr vajíček, kterou najdete ve zprávách a rozpisech z kliniky.',
    long: 'Označuje výkon, při kterém se z folikulů tenkou jehlou odsaje tekutina a embryolog v ní hledá vajíčka. Ve zprávě bývá u OPU počet folikulů a počet skutečně získaných oocytů — tato dvě čísla se běžně liší a nižší počet vajíček není znakem pochybení. Datum OPU je zároveň nultým dnem vývoje embryí, od kterého se počítají všechny další dny.',
    topics: ['klinika', 'embryologie', 'vysledky'],
  },
  {
    term: 'Oocyt',
    aliases: ['vajíčko', 'ovum'],
    short: 'Ženská pohlavní buňka, ze které po oplození vzniká embryo.',
    long: 'Vzniká ve vaječníku uvnitř folikulu a je největší buňkou lidského těla, přesto pouhým okem neviditelnou. Zásoba oocytů je daná od narození a v čase klesá počtem i kvalitou — proto věk hraje roli, kterou léčba neobrátí. Ne každý odebraný oocyt je zralý a ne každý zralý se oplodní; úbytek v každém kroku je očekávaný, ne výjimečný.',
    topics: ['embryologie', 'vysledky'],
  },
  {
    term: 'MII',
    aliases: ['metafáze II', 'MII oocyt'],
    short: 'Označení zralého vajíčka ve zprávě z laboratoře — jen takové se dá oplodnit.',
    long: 'Znamená, že vajíčko dokončilo první zrací dělení a vypudilo pólové tělísko. Zralost lze spolehlivě posoudit až po odstranění obalových buněk, tedy hlavně před ICSI. Ve zprávě proto můžete vidět třeba „12 oocytů, z toho 9 MII" — to nižší číslo je to, se kterým laboratoř dál pracuje.',
    topics: ['embryologie', 'vysledky'],
  },
  {
    term: 'Nezralý oocyt',
    aliases: ['MI', 'GV oocyt', 'nezralé vajíčko'],
    short: 'Vajíčko, které v době odběru ještě nedozrálo, a proto se obvykle nedá oplodnit.',
    long: 'Označuje se jako GV, pokud má ještě viditelné jádro, nebo MI, pokud je zrání rozběhnuté, ale nedokončené. Část nezralých vajíček dozraje v laboratoři během několika hodin, spolehnout se na to ale nejde. Určitý podíl nezralých vajíček je v každém cyklu běžný a nevypovídá o kvalitě těch ostatních.',
    topics: ['embryologie', 'vysledky'],
  },
  {
    term: 'Denudace oocytů',
    aliases: ['odstranění kumulárních buněk'],
    short: 'Odstranění obalových buněk kolem vajíčka, bez kterého nelze posoudit jeho zralost.',
    long: 'Provádí se před ICSI, obvykle několik hodin po odběru, kombinací enzymu a jemného pipetování. Teprve po něm embryolog vidí, kolik vajíček je zralých. Při konvenčním IVF obalové buňky zůstávají a zralost se pozná až podle výsledku oplození — proto při něm počet MII vůbec slyšet nemusíte.',
    topics: ['embryologie'],
  },
  {
    term: 'Syndrom prázdných folikulů',
    aliases: ['prázdné folikuly'],
    short: 'Vzácná situace, kdy se přes dobrý ultrazvukový nález nezíská při odběru žádné vajíčko.',
    long: 'Někdy souvisí s načasováním nebo aplikací triggeru, jindy se příčina nenajde. Neznamená to, že ve vaječnících žádná vajíčka nejsou. Po takovém cyklu se obvykle podrobně prochází čas a způsob podání spouštěcí injekce a další postup se plánuje individuálně. Je to jedna z nejtěžších zpráv celého cyklu a je v pořádku ji tak prožívat.',
    topics: ['embryologie', 'psychika'],
  },

  // --- Oplození a vývoj embrya -------------------------------------------
  {
    term: '2PN',
    aliases: ['dvě prvojádra', 'pronuklea', 'normální oplození'],
    short: 'Nález dvou prvojader den po odběru — znamení, že oplození proběhlo správně.',
    long: 'Jedno prvojádro nese genetickou informaci z vajíčka, druhé ze spermie; ještě nesplynula, ale jsou vedle sebe vidět. Kontroluje se v úzkém časovém okně zhruba 16 až 18 hodin po oplození, protože potom prvojádra mizí. Číslo 2PN v prvním telefonátu z laboratoře je první konkrétní údaj o tom, kolik embryí máte.',
    topics: ['embryologie', 'vysledky'],
  },
  {
    term: 'Abnormální oplození',
    aliases: ['1PN', '3PN'],
    short: 'Nález s jiným počtem prvojader než dvěma; taková embrya se obvykle dál nepoužívají.',
    long: 'Jedno prvojádro může znamenat, že se genetická informace spojila jinak, tři obvykle vstup více spermií nebo nevypuzené pólové tělísko. Riziko chybného počtu chromozomů je vysoké, proto se tato embrya standardně ke kultivaci a přenosu nezařazují. Určitý podíl abnormálně oplozených vajíček se objevuje běžně a není znakem chyby laboratoře.',
    topics: ['embryologie', 'genetika'],
  },
  {
    term: 'Míra oplození',
    aliases: ['fertilizační rate', 'úspěšnost oplození'],
    short: 'Podíl zralých vajíček, u kterých laboratoř den po odběru potvrdila správné oplození.',
    long: 'Počítá se ze zralých vajíček, ne ze všech odebraných — proto se procenta v různých zprávách liší a nejde je porovnávat bez kontextu. Nižší hodnota v jednom cyklu sama o sobě nic nediagnostikuje; opakovaně nízká bývá důvodem k přehodnocení způsobu oplození. Vysoká míra oplození zároveň nezaručuje, že do stadia blastocysty dorostou všechna embrya.',
    topics: ['embryologie', 'vysledky'],
  },
  {
    term: 'Selhání oplození',
    aliases: ['nulové oplození', 'total fertilization failure'],
    short: 'Situace, kdy se neoplodní žádné z odebraných vajíček.',
    long: 'Příčina může být na straně spermií, vajíček i jejich vzájemné interakce a v části případů se nenajde. Po konvenčním IVF bývá v dalším cyklu zvažováno ICSI, po ICSI se hledá jiné vysvětlení. Je to zdrcující zpráva, která přichází telefonem v den, kdy jste čekala počty embryí. Zaslouží si samostatný rozhovor s lékařem, ne jen větu do telefonu.',
    topics: ['embryologie', 'psychika'],
  },
  {
    term: 'Rýhování',
    aliases: ['cleavage', 'dělení embrya', 'rýhující se embryo'],
    short: 'Fáze druhého až třetího dne, kdy se embryo dělí na stále menší buňky.',
    long: 'Embryo se v této době nezvětšuje — dělí se uvnitř původního obalu, takže buňky jsou čím dál drobnější. Druhý den se očekávají zhruba čtyři buňky, třetí den zhruba osm, přičemž rozptyl je běžný. Právě v tomto období přebírá embryo řízení z materiálu vajíčka na vlastní program, a proto se část embryí dál nevyvíjí.',
    topics: ['embryologie'],
  },
  {
    term: 'Blastomera',
    aliases: ['buňka embrya'],
    short: 'Jedna z buněk, na které se embryo v prvních dnech vývoje dělí.',
    long: 'Ve zprávách se počet blastomer píše jako číslo, například „8 buněk, 10 % fragmentace". Hodnotí se také to, jestli jsou buňky stejně velké — výrazně nestejné dělení bývá spojováno s horším vývojem. Počet buněk je vodítko, ne verdikt; embryo se posuzuje ze všech parametrů dohromady.',
    topics: ['embryologie', 'vysledky'],
  },
  {
    term: 'Fragmentace embrya',
    aliases: ['fragmenty v embryu'],
    short: 'Drobné úlomky buněčné hmoty mezi buňkami embrya, které se popisují v procentech.',
    long: 'Nejde o fragmentaci DNA spermií — to je úplně jiné vyšetření a týká se muže. Malý podíl fragmentů má naprostá většina embryí a dalšímu vývoji bránit nemusí. Vyšší podíl se v hodnocení promítne do horšího skóre, ale ani ten sám o sobě o osudu embrya nerozhoduje.',
    topics: ['embryologie', 'vysledky'],
  },
  {
    term: 'Kompaktace',
    aliases: ['kompaktující se embryo'],
    short: 'Okamžik, kdy se buňky embrya k sobě přimknou a jejich hranice přestanou být patrné.',
    long: 'Nastává obvykle čtvrtý den a vede ke vzniku moruly. Protože se buňky nedají spočítat, čtvrtý den se často žádná čísla nehlásí — laboratoř mlčí proto, že není co měřit, ne proto, že by šlo o špatnou zprávu. Opožděná nebo neúplná kompaktace bývá popisována jako méně příznivý průběh.',
    topics: ['embryologie'],
  },
  {
    term: 'Dny vývoje embrya',
    aliases: ['D1 až D6', 'den kultivace', 'D3', 'D5'],
    short: 'Číslování dnů od odběru vajíček, podle kterého se popisuje vývoj embrya.',
    long: 'Den odběru je nultý, první den se hodnotí oplození, druhý a třetí den rýhování, čtvrtý morula a pátý až šestý blastocysta. Embrya se tedy sledují po celou dobu, ne až od blastocysty — každý den má vlastní očekávaný nález. Embryo, které dorostlo do blastocysty až šestý den, je pomalejší, ne automaticky horší. Přenos se podle situace provádí třetí, pátý i šestý den.',
    topics: ['embryologie', 'vysledky'],
  },
  {
    term: 'Trofektoderm',
    aliases: ['trofoblast', 'vnější vrstva blastocysty'],
    short: 'Vnější vrstva buněk blastocysty, ze které vzniká placenta a obaly, ne samotné dítě.',
    long: 'Právě z ní se odebírá vzorek při preimplantačním genetickém testování, aby se nezasahovalo do buněk budoucího plodu. To má i svou nevýhodu: výsledek popisuje odebrané buňky, nikoli celé embryo. V hodnocení blastocysty ji popisuje druhé písmeno.',
    topics: ['embryologie', 'genetika'],
  },
  {
    term: 'Vnitřní buněčná masa',
    aliases: ['ICM', 'embryoblast'],
    short: 'Shluk buněk uvnitř blastocysty, ze kterého se vyvíjí samotný plod.',
    long: 'V hodnocení blastocysty ji popisuje první písmeno — sleduje se, jak je zřetelná a jak těsně jsou buňky u sebe. Hodnocení je vizuální a částečně subjektivní, takže stejné embryo může být na dvou pracovištích popsáno mírně jinak. Vzhled vnitřní buněčné masy nevypovídá o genetice embrya.',
    topics: ['embryologie', 'vysledky'],
  },
  {
    term: 'Zona pellucida',
    aliases: ['obal vajíčka', 'průsvitný obal'],
    short: 'Pružný obal kolem vajíčka a časného embrya, který ho chrání a drží pohromadě.',
    long: 'Skrz něj se při ICSI zavádí jehla a z něj se blastocysta před uhnízděním musí dostat ven. Bývá popisován jako silnější například u starších pacientek nebo po vitrifikaci, i když jeho měření není přesné. Právě představa ztluštělého obalu stojí za nabídkou asistovaného hatchingu.',
    topics: ['embryologie'],
  },
  {
    term: 'Asistovaný hatching',
    aliases: ['AH', 'narušení obalu embrya'],
    short: 'Laboratorní zásah, při kterém se obal embrya před přenosem jemně naruší laserem.',
    long: 'Má embryu usnadnit vylíhnutí z obalu, které uhnízdění předchází. Důkazy o tom, že by vedl k vyšší šanci na živě narozené dítě, jsou nejednoznačné, a proto nejde o rutinní součást každého cyklu. Nabízen bývá u rozmrazených embryí, u starších pacientek nebo po opakovaném neúspěchu. Zeptejte se, z čeho vaše klinika u vás vychází.',
    topics: ['embryologie', 'transfer'],
  },
  {
    term: 'Grading',
    aliases: ['hodnocení embryí', 'skóre embrya', 'Gardnerova škála'],
    short: 'Popis vzhledu embrya čísly a písmeny, podle kterého se embrya řadí k přenosu.',
    long: 'Třetí den se hodnotí počet buněk, jejich souměrnost a podíl fragmentace, u blastocysty stupeň rozvinutí a obě skupiny buněk — nejrozšířenější je Gardnerova škála, odtud zápisy typu 4AA. Popisuje vzhled pod mikroskopem, ne genetiku a ne budoucnost konkrétního embrya. Hodnocení je částečně subjektivní a mezi laboratořemi ne zcela srovnatelné. Slouží k seřazení vašich embryí mezi sebou, ne k předpovědi výsledku.',
    topics: ['embryologie', 'vysledky'],
  },

  // --- Kryokonzervace -----------------------------------------------------
  {
    term: 'Kryokonzervace',
    aliases: ['zamrazení', 'kryo'],
    short: 'Uchování buněk nebo embryí při teplotě tekutého dusíku, kdy se všechny děje zastaví.',
    long: 'Zamrazovat lze embrya, vajíčka, spermie i tkáň vaječníku. Dnes se téměř výhradně používá vitrifikace, tedy ultrarychlé zmrazení, které nahradilo starší pomalou metodu. Doba uchování je omezená smlouvou a předpisy, ne biologicky. Za skladování se obvykle platí a vyplatí se dopředu vědět kolik a jak často.',
    topics: ['embryologie', 'finance', 'klinika'],
  },
  {
    term: 'Kryoprotektant',
    aliases: ['ochranná látka při mrazení'],
    short: 'Látka, která před zamrazením nahradí část vody v buňce a zabrání vzniku ledu.',
    long: 'Embryo se před vitrifikací v několika krocích těmito látkami prosytí a po rozmrazení se stejně opatrně vymývají. Právě tento krok, ne samotný mráz, rozhoduje o tom, jestli buňka zamrazení přežije. Jde o rutinní laboratorní postup, jehož provedení se ale mezi pracovišti může lišit.',
    topics: ['embryologie'],
  },
  {
    term: 'Rozmrazení',
    aliases: ['devitrifikace', 'ohřev embrya'],
    short: 'Návrat embrya nebo vajíčka z hlubokého mrazu do podmínek, ve kterých může dál žít.',
    long: 'Probíhá v den transferu nebo den předem a trvá jen několik minut. Většina vitrifikovaných blastocyst rozmrazení přežije, u konkrétního embrya to ale zaručit nejde — proto se vždy počítá s tím, že se plán může změnit. Embryolog po rozmrazení posuzuje, jestli se embryo znovu rozepnulo. Jak si vaše embryo vedlo, se dozvíte tentýž den.',
    topics: ['embryologie', 'transfer'],
  },
  {
    term: 'Skladování embryí',
    aliases: ['úschova embryí', 'kryobanka'],
    short: 'Uchovávání zamrazených embryí v kryobance na základě smlouvy a písemného souhlasu.',
    long: 'Skladování je zpoplatněné, obnovuje se na určité období a vyžaduje souhlas obou partnerů. S embryi se pojí i rozhodnutí, která se nikomu nepromýšlejí snadno — co s nimi při rozchodu, po dokončení rodiny nebo po uplynutí smluvené doby. Vyplatí se znát podmínky své kliniky dřív, než na ně dojde. Pravidla se mohou lišit a patří k dotazům na kliniku.',
    topics: ['klinika', 'finance', 'vztah'],
  },

  // --- Transfer -----------------------------------------------------------
  {
    term: 'Čerstvý embryotransfer',
    aliases: ['čerstvý transfer', 'fresh transfer'],
    short: 'Přenos embrya ve stejném cyklu, ve kterém proběhl odběr vajíček, bez zamrazení.',
    long: 'Probíhá obvykle třetí až pátý den po odběru. Výhodou je kratší cesta k výsledku, nevýhodou to, že tělo je čerstvě po stimulaci a hladiny hormonů jsou vysoké. Při riziku OHSS, vyšším progesteronu nebo nevhodné sliznici se od čerstvého transferu upouští a embrya se zamrazují. Ani jedna varianta není univerzálně lepší; volba je individuální.',
    topics: ['transfer', 'klinika'],
  },
  {
    term: 'FET',
    aliases: ['frozen embryo transfer', 'kryotransfer'],
    short: 'Anglická zkratka pro přenos rozmrazeného embrya — česky kryoembryotransfer, KET.',
    long: 'Objevuje se ve zprávách, v odborných textech i na zahraničních webech. Z jednoho odběru může vzniknout několik takových přenosů, protože embrya se zamrazují po jednom nebo po dvou. Příprava sliznice probíhá buď v přirozeném, nebo v substituovaném cyklu. Úspěšnost uváděnou „na FET" nelze srovnávat s čísly uváděnými na cyklus.',
    topics: ['transfer', 'vysledky'],
  },
  {
    term: 'Substituovaný cyklus',
    aliases: ['HRT cyklus', 'umělý cyklus', 'medikamentózní příprava sliznice'],
    short: 'Příprava na kryotransfer, při které sliznici řídí podávaný estrogen a progesteron.',
    long: 'Vlastní ovulace se obvykle potlačí a tělo dostane hormony zvenčí, takže se termín přenosu dá naplánovat na den dopředu. Od začátku progesteronu se načasování transferu odvíjí na hodiny, proto se časy dávek nemají posouvat. Léky se zpravidla užívají i po transferu, dokud o jejich ukončení nerozhodne lékař. Volba mezi substituovaným a přirozeným cyklem je individuální.',
    topics: ['transfer', 'leky', 'hormony'],
  },
  {
    term: 'Přirozený cyklus KET',
    aliases: ['nativní cyklus', 'modifikovaný přirozený cyklus'],
    short: 'Příprava na kryotransfer, která se opírá o vaši vlastní ovulaci a žluté tělísko.',
    long: 'Sleduje se růst folikulu a sliznice a přenos se načasuje podle ovulace, někdy dokončené triggerem. Léků je méně, ale termín se řídí tělem, ne kalendářem, takže se hůř plánuje a vyžaduje častější kontroly. Předpokladem jsou pravidelné cykly s ovulací. Podpora luteální fáze se i tak často přidává a rozhoduje o ní lékař.',
    topics: ['transfer', 'hormony'],
  },
  {
    term: 'Elektivní jednoembryový transfer',
    aliases: ['eSET', 'SET', 'přenos jednoho embrya'],
    short: 'Záměrný přenos jediného embrya, i když je jich k dispozici víc.',
    long: 'Hlavním důvodem je vyhnout se dvojčatům — vícečetné těhotenství s sebou nese vyšší rizika pro matku i pro děti. Zbylá embrya se zamrazí a použijí v dalších transferech, takže se šance z jednoho odběru neztrácí, jen rozloží v čase. Přenos dvou embryí zvyšuje pravděpodobnost dvojčat výrazněji než pravděpodobnost, že si domů odnesete dítě. Počet přenášených embryí patří k rozhovoru s lékařem před transferem.',
    topics: ['transfer', 'klinika'],
  },
  {
    term: 'Zkušební transfer',
    aliases: ['mock transfer', 'probní transfer'],
    short: 'Nácvik zavedení katétru bez embrya, který předem zmapuje tvar děložního kanálu.',
    long: 'Provádí se před cyklem nebo před samotným transferem a trvá pár minut. Lékař si změří délku dutiny a zjistí, jestli je průchod hrdlem hladký, nebo bude potřeba jiný typ katétru. Cílem je, aby v den transferu nic nepřekvapilo. Nepříjemný zkušební transfer neznamená, že bude nepříjemný i ten skutečný.',
    topics: ['transfer', 'klinika'],
  },
  {
    term: 'EmbryoGlue',
    aliases: ['médium s hyaluronanem', 'transferové médium'],
    short: 'Transferové médium s vyšším obsahem hyaluronanu, ve kterém se embryo přenáší.',
    long: 'Hustší kapka má podle úvahy zlepšit kontakt embrya se sliznicí; embryo se ale nikam nelepí a název je marketingový. Data jsou smíšená a nedovolují tvrdit, že by přípravek zvyšoval šanci na těhotenství. Bývá nabízen za příplatek. Když vám ho klinika navrhne, je namístě zeptat se, proč právě u vás a co od toho čeká.',
    topics: ['transfer', 'embryologie', 'finance'],
  },
  {
    term: 'Sanakin',
    aliases: ['autologní kondiciované sérum', 'intrauterinní instilace séra'],
    short: 'Přípravek z vlastní krve, který se před transferem zavádí do dutiny děložní.',
    long: 'Krev se odebere, zpracuje a získaná tekutina se aplikuje do dělohy s cílem ovlivnit místní imunitní prostředí. Používá se hlavně po opakovaném selhání implantace. Důkazy o vlivu na šanci na těhotenství jsou zatím slabé a metoda nepatří mezi standardní postupy. Pokud vám ji klinika nabídne, ptejte se na cenu, na očekávaný přínos a na to, co se o něm skutečně ví.',
    topics: ['transfer', 'klinika', 'finance'],
  },
  {
    term: 'Scratching',
    aliases: ['endometriální scratch', 'poškrábání sliznice', 'pipelle'],
    short: 'Záměrné drobné poranění děložní sliznice v cyklu předcházejícím transferu.',
    long: 'Vychází z úvahy, že hojení sliznice zlepší její vnímavost k embryu. Velké randomizované studie ale přínos pro šanci na živě narozené dítě nepotvrdily, a proto se od plošného používání ustupuje. Výkon bývá bolestivý a není zcela bez rizika. Pokud vám ho někdo nabídne, ptejte se, co konkrétně od něj ve vaší situaci očekává.',
    topics: ['transfer', 'klinika'],
  },
  {
    term: 'PRP',
    aliases: ['plazma bohatá na destičky', 'intrauterinní PRP', 'ovariální PRP'],
    short: 'Zavedení koncentrátu vlastních krevních destiček do dělohy nebo do vaječníku.',
    long: 'Zkouší se u velmi tenké sliznice a u nízké ovariální rezervy s cílem podpořit místní regeneraci. Jde o experimentální postup: publikované soubory jsou malé a kvalitní důkazy o vlivu na těhotenství a na živě narozené dítě chybí. Nelze ho označit za léčbu, která by měla být nabízena běžně. Rozhodnutí patří vám a vašemu lékaři, s realistickým očekáváním a se znalostí ceny.',
    topics: ['transfer', 'klinika', 'finance'],
  },
  {
    term: 'Receptivita endometria',
    aliases: ['vnímavost sliznice'],
    short: 'Stav, kdy je děložní sliznice schopná přijmout embryo a umožnit uhnízdění.',
    long: 'Řídí ji především progesteron a doba jeho působení, ne pouze tloušťka sliznice na ultrazvuku. Snaha ji přesně změřit je předmětem výzkumu a testy, které to slibují, zatím nemají jednoznačně prokázaný přínos pro výsledek léčby. Sliznice, která vypadá dobře, proto není zárukou — a naopak. Co má u vás smysl vyšetřovat, patří k rozhovoru s lékařem.',
    topics: ['transfer', 'hormony'],
  },
  {
    term: 'Trilaminární endometrium',
    aliases: ['trojvrstevná sliznice', 'trojlaminární obraz'],
    short: 'Ultrazvukový obraz sliznice před ovulací, kdy jsou patrné tři vrstvy.',
    long: 'Popisuje vzhled, ne funkci — hodnotí se vždy spolu s tloušťkou a s fází cyklu. Po nástupu progesteronu obraz mizí, což je očekávaná změna, ne zhoršení. Jednotlivý popis ve zprávě sám o sobě neurčuje, jestli transfer proběhne; rozhoduje lékař z celkového nálezu.',
    topics: ['transfer', 'vysledky'],
  },
  {
    term: 'Tenká děložní sliznice',
    aliases: ['tenké endometrium'],
    short: 'Sliznice, která před transferem nedosáhne tloušťky považované pracovištěm za dostatečnou.',
    long: 'Příčinou bývá stav po výkonech v dutině děložní, srůsty, chronický zánět nebo slabší odpověď na estrogeny; často se příčina nenajde. Postupy se liší — delší podávání estrogenů, jiná cesta podání, změna typu cyklu nebo hysteroskopie k vyloučení nálezu v dutině. Hraniční tloušťka není u každé ženy překážkou a hodnotí se v souvislostech. Co dělat dál, určuje váš lékař.',
    topics: ['transfer', 'hormony'],
  },
  {
    term: 'Formy progesteronu',
    aliases: ['vaginální progesteron', 'injekční progesteron'],
    short: 'Různé cesty podání progesteronu po transferu — vaginálně, do svalu nebo ústy.',
    long: 'Vaginální podání působí přímo v děloze, injekce do svalu dává vysoké hladiny v krvi, podání ústy má nižší využitelnost a používá se spíš v kombinaci. Hladina v krvi neodpovídá účinku v děloze, proto se u vaginální formy samotné měření běžně neinterpretuje. Vedlejší účinky se liší podle formy: podráždění a výtok, bolestivá místa vpichu, útlum a únava. Formu, dávku i délku určuje lékař — sama je neměňte.',
    topics: ['leky', 'hormony', 'transfer'],
  },

  // --- Děloha a diagnostika ----------------------------------------------
  {
    term: 'Chronická endometritida',
    aliases: ['chronický zánět sliznice'],
    short: 'Dlouhodobý mírný zánět děložní sliznice, který nemusí dělat žádné potíže.',
    long: 'Zjišťuje se z odběru vzorku sliznice, obvykle při hysteroskopii, se speciálním barvením. Bývá zvažována po opakovaném selhání implantace nebo po opakovaných ztrátách těhotenství. Léčí se antibiotiky podle nálezu a po léčbě se obvykle kontroluje. Vyšetření není součástí základního programu pro každou ženu a jeho indikaci určuje lékař.',
    topics: ['transfer', 'klinika'],
  },
  {
    term: 'Děložní polyp',
    aliases: ['endometriální polyp'],
    short: 'Výrůstek děložní sliznice do dutiny, který se najde na ultrazvuku nebo hysteroskopii.',
    long: 'Může způsobovat špinění mezi cykly nebo silnější krvácení, často ale nedělá vůbec nic. Podle velikosti a umístění bývá před transferem zvažováno jeho hysteroskopické odstranění. Zákrok je krátký a odebraná tkáň se obvykle posílá na histologické vyšetření. Ne každý nález se musí odstraňovat — rozhoduje lékař.',
    topics: ['transfer', 'klinika'],
  },
  {
    term: 'Děložní myom',
    aliases: ['myom', 'fibrom'],
    short: 'Nezhoubný útvar ze svaloviny dělohy; jeho význam závisí hlavně na uložení.',
    long: 'Myomy zasahující do dutiny děložní jsou z hlediska uhnízdění nejsledovanější, myomy ve stěně nebo na povrchu často léčbu neovlivní. Postup se řídí velikostí, počtem, potížemi a plánem léčby — někdy hysteroskopicky, jindy jinou operací. Odstranění není namístě u každého nálezu a rekonvalescence může posunout termín transferu. Rozhodnutí patří lékaři.',
    topics: ['klinika', 'transfer'],
  },
  {
    term: 'Děložní septum',
    aliases: ['přepážka v děloze', 'septovaná děloha'],
    short: 'Vrozená přepážka, která částečně nebo úplně rozděluje dutinu děložní.',
    long: 'Patří k vrozeným odchylkám tvaru dělohy a bývá spojována s opakovanými ztrátami těhotenství. Zobrazí se ultrazvukem, nejlépe trojrozměrným, nebo hysteroskopií. Protětí přepážky je krátký hysteroskopický výkon; jeho přínos se posuzuje individuálně a odborná diskuse pokračuje. Samotný nález neznamená, že otěhotnět nejde.',
    topics: ['klinika', 'ztrata'],
  },
  {
    term: 'Endometriální biopsie',
    aliases: ['odběr vzorku sliznice', 'pipelle biopsie'],
    short: 'Odběr drobného vzorku děložní sliznice tenkou kanylou, obvykle přímo v ambulanci.',
    long: 'Používá se k vyloučení chronického zánětu, k histologickému posouzení nebo jako vzorek pro testy vnímavosti sliznice. Trvá krátce, provádí se bez narkózy a bývá nepříjemný, podobně jako silnější menstruační křeč. Den odběru v cyklu je zásadní a určuje ho lékař. Není to vyšetření, které by potřebovala každá žena.',
    topics: ['klinika', 'transfer'],
  },
  {
    term: 'Salpingektomie',
    aliases: ['odstranění vejcovodu'],
    short: 'Operační odstranění vejcovodu, nejčastěji laparoskopicky.',
    long: 'Zvažuje se hlavně u hydrosalpingu, tedy vejcovodu naplněného tekutinou, protože ta může zatékat do dutiny děložní. Provádí se také při mimoděložním těhotenství, pokud vejcovod nelze zachovat. Odstranění vejcovodu neubírá vaječníku vajíčka, ale uzavírá cestu k přirozenému otěhotnění na dané straně. Indikaci posuzuje lékař individuálně.',
    topics: ['klinika'],
  },
  {
    term: 'TESE',
    aliases: ['TESA', 'micro-TESE', 'chirurgický odběr spermií'],
    short: 'Odběr spermií přímo z tkáně varlete v situaci, kdy v ejakulátu žádné nejsou.',
    long: 'Provádí se jehlou nebo drobným řezem, podle situace i s mikroskopem, který zvyšuje šanci najít ložiska tvorby spermií. Získané spermie se používají výhradně k ICSI a část vzorku lze zamrazit. Ne u každého muže se spermie najdou a výsledek nelze předem slíbit. O vhodnosti výkonu rozhoduje urolog nebo androlog společně s reprodukčním centrem.',
    topics: ['partner', 'embryologie'],
  },
  {
    term: 'Azoospermie',
    short: 'Nález, kdy se v ejakulátu opakovaně nenajde žádná spermie.',
    long: 'Rozlišuje se obstrukční, kde je tvorba spermií zachovaná a překážka leží v odvodných cestách, a neobstrukční, kde je porucha tvorby ve varleti. Rozlišení určuje další postup a vyžaduje hormonální, genetické a urologické vyšetření. U části mužů lze spermie získat výkonem přímo z varlete. Diagnóza se nikdy nestanovuje z jediného vzorku.',
    topics: ['partner', 'vysledky'],
  },

  // --- Genetika -----------------------------------------------------------
  {
    term: 'PGT',
    aliases: ['preimplantační genetické testování'],
    short: 'Souhrnný název pro genetické testování embryí ještě před jejich přenosem.',
    long: 'Zahrnuje testování počtu chromozomů, testování konkrétní dědičné nemoci v rodině a testování u nositelů chromozomových přestaveb. Vždy vyžaduje IVF, odběr buněk z embrya a zamrazení, takže se přenos odkládá do dalšího cyklu. Netvoří lepší embrya, jen vybírá z těch, která vznikla — a při malém počtu embryí nemusí zbýt žádné vhodné. Indikaci posuzuje lékař společně s klinickým genetikem.',
    topics: ['genetika', 'embryologie'],
  },
  {
    term: 'Biopsie trofektodermu',
    aliases: ['odběr buněk z embrya', 'biopsie embrya'],
    short: 'Odebrání několika buněk z vnější vrstvy blastocysty pro genetické vyšetření.',
    long: 'Provádí se obvykle pátý až šestý den pomocí laseru a embryo se ihned poté vitrifikuje. Odebírají se buňky budoucí placenty, ne budoucího plodu — proto výsledek popisuje jen tuto část embrya. Zákrok do embrya zasahuje, a přestože se v dobrých laboratořích považuje za bezpečný, není bez rizika. Provádí se jen tam, kde pro testování existuje důvod.',
    topics: ['genetika', 'embryologie'],
  },
  {
    term: 'Aneuploidní embryo',
    aliases: ['aneuploidie'],
    short: 'Embryo, u kterého testování našlo chybějící nebo nadbytečný chromozom.',
    long: 'Většina takových embryí se neuchytí nebo těhotenství brzy skončí; některé odchylky jsou slučitelné s narozením dítěte se závažným postižením. Podíl aneuploidních embryí přirozeně stoupá s věkem ženy a netýká se jen IVF — vznikají i při přirozeném početí, jen o nich nikdo neví. Nález nevypovídá o vás ani o vašem partnerovi a nikdo ho nezpůsobil. Výsledek se probírá na genetické konzultaci.',
    topics: ['genetika', 'embryologie', 'psychika'],
  },
  {
    term: 'Nekonklusivní výsledek PGT',
    aliases: ['nevýtěžný vzorek', 'výsledek bez závěru'],
    short: 'Situace, kdy laboratoř ze vzorku odebraného z embrya nezíská hodnotitelný výsledek.',
    long: 'Důvodem bývá málo buněk, jejich poškození nebo technický problém při zpracování. Neznamená to, že je embryo špatné. Podle situace lze zvážit opakovanou biopsii po rozmrazení, nebo se o embryu rozhoduje bez genetického výsledku. Co je vhodné u vás, proberte s klinickým genetikem a se svou klinikou.',
    topics: ['genetika', 'embryologie'],
  },
  {
    term: 'Opakované selhání implantace',
    aliases: ['RIF', 'opakovaně neúspěšné transfery'],
    short: 'Označení pro situaci, kdy se ani po několika přenesených embryích těhotenství nezaloží.',
    long: 'Jednotná definice neexistuje; obvykle se mluví o několika transferech dobrých embryí bez známky uhnízdění. Hledají se příčiny na straně embryí, dělohy, hormonů i celkového zdraví, u části párů se ale žádná nenajde. Nabídka doplňkových metod je právě v této situaci největší a zároveň nejméně podložená — u každé z nich se ptejte na důkazy a na cenu. Další postup patří k rozhovoru s lékařem.',
    topics: ['transfer', 'psychika', 'klinika'],
  },
  {
    term: 'NK buňky',
    aliases: ['natural killer buňky', 'imunologie implantace'],
    short: 'Buňky imunitního systému, které se vyšetřují v souvislosti s uhnízděním embrya.',
    long: 'Buňky v děloze se liší od těch v krvi a jejich přítomnost je normální součástí přípravy sliznice na těhotenství, ne známkou útoku na embryo. Vyšetření z krve se běžně nabízí, ale jeho výpovědní hodnota pro reprodukci je předmětem sporu. Mezinárodní doporučení zatím plošné testování ani léčbu podle jeho výsledku mimo výzkum nepodporují. Pokud vám ho někdo nabídne, ptejte se, co by se podle výsledku změnilo.',
    topics: ['klinika', 'vysledky'],
  },
  {
    term: 'Intralipid',
    aliases: ['tuková emulze', 'imunomodulační infuze'],
    short: 'Nitrožilní tuková emulze podávaná v rámci takzvané imunologické léčby neplodnosti.',
    long: 'Původně jde o přípravek pro výživu do žíly, který se v reprodukci používá mimo svou schválenou indikaci. Kvalitní důkazy o tom, že by zvyšoval šanci na těhotenství nebo na živě narozené dítě, chybí. Odborné společnosti ho proto mimo výzkum běžně nedoporučují. Než na něj přistoupíte, proberte s lékařem, co se od něj čeká a kolik bude stát.',
    topics: ['leky', 'klinika', 'finance'],
  },
  {
    term: 'Nízkomolekulární heparin',
    aliases: ['LMWH', 'injekce na ředění krve'],
    short: 'Injekční lék snižující srážlivost krve, používaný u vybraných diagnóz.',
    long: 'Má jasné místo tam, kde je prokázaná porucha srážlivosti nebo antifosfolipidový syndrom, případně při vysokém riziku trombózy. Plošné podávání všem ženám po transferu ale prospěch neprokázalo a namístě není. Aplikuje se podkožně a modřiny v místě vpichu jsou běžné. O nasazení i vysazení rozhoduje výhradně lékař.',
    topics: ['leky', 'klinika'],
  },

  // --- Rané těhotenství ---------------------------------------------------
  {
    term: 'Klinické těhotenství',
    short: 'Těhotenství potvrzené ultrazvukem, ne jen hodnotou hCG v krvi.',
    long: 'Za potvrzené se považuje ve chvíli, kdy je vidět gestační váček, obvykle zhruba od pátého týdne. Tím se liší od biochemického těhotenství, které skončí dřív, než by šlo cokoli zobrazit. Úspěšnost léčby se často uvádí právě jako podíl klinických těhotenství, což je jiné číslo než podíl porodů. Když čtete statistiky, hlídejte si, co přesně se v nich počítá.',
    topics: ['tehotenstvi', 'vysledky'],
  },
  {
    term: 'Žloutkový váček',
    aliases: ['yolk sac'],
    short: 'Drobná kulatá struktura uvnitř gestačního váčku, viditelná dřív než samotný zárodek.',
    long: 'Bývá patrný zhruba od pátého až šestého týdne a je prvním znakem, že se v gestačním váčku něco vyvíjí. Jeho velikost a vzhled hodnotí lékař v souvislostech; jednotlivý popis sám o sobě nic neurčuje. To, že ještě není vidět zárodek ani srdeční akce, nemusí v tomto období nic znamenat — záleží na přesném stáří těhotenství.',
    topics: ['tehotenstvi', 'vysledky'],
  },
  {
    term: 'Embryonální ozvěna',
    aliases: ['srdeční akce', 'akce srdeční', 'ozvy'],
    short: 'Srdeční činnost zárodku viditelná na ultrazvuku, obvykle zhruba od šestého týdne.',
    long: 'Bývá prvním okamžikem, kdy se těhotenství přestane počítat jen z čísel a začne se na ně dívat. Že není vidět při první kontrole, nemusí být špatná zpráva — i u IVF, kde se stáří počítá přesně, hraje roli rozdíl několika dní. Lékař v takové situaci obvykle navrhne kontrolu s odstupem. Výklad nálezu patří jemu, ne kalkulačkám na internetu.',
    topics: ['tehotenstvi', 'cekani', 'psychika'],
  },
  {
    term: 'Těhotenství neznámé lokalizace',
    aliases: ['PUL'],
    short: 'Stav, kdy je hCG pozitivní, ale ultrazvuk zatím neukáže, kde těhotenství je.',
    long: 'Není to diagnóza, ale dočasné zařazení — může jít o velmi rané nitroděložní těhotenství, o těhotenství, které se ukončuje, i o mimoděložní. Postupuje se opakovanými odběry hCG z krve a kontrolními ultrazvuky v krátkých odstupech. Termíny kontrol je důležité dodržet. Při prudké bolesti břicha, závrati nebo mdlobě vyhledejte akutní lékařskou pomoc.',
    topics: ['tehotenstvi', 'vysledky', 'ztrata'],
  },
  {
    term: 'Heterotopické těhotenství',
    short: 'Vzácná situace, kdy se současně vyvíjí těhotenství v děloze i mimo ni.',
    long: 'Po IVF bývá popisováno častěji než po přirozeném početí, přesto zůstává vzácné. Nález gestačního váčku v děloze proto mimoděložní těhotenství zcela nevylučuje. Varovné jsou prudká jednostranná bolest břicha, závrať nebo mdloba — v takovém případě vyhledejte akutní lékařskou pomoc a řekněte, že jste po embryotransferu.',
    topics: ['tehotenstvi', 'ztrata'],
  },
  {
    term: 'Kumulativní šance',
    aliases: ['kumulativní úspěšnost', 'šance z jednoho odběru'],
    short: 'Souhrnná pravděpodobnost porodu ze všech transferů, které z jednoho odběru vzejdou.',
    long: 'Počítá dohromady čerstvý transfer i všechny následné kryotransfery ze stejné zásoby embryí. Je to poctivější číslo než úspěšnost jednoho transferu, protože odpovídá tomu, jak léčba doopravdy probíhá. Závisí především na věku ženy v době odběru a na počtu vzniklých embryí. Konkrétní odhad pro vaši situaci umí dát jen váš lékař — a i pak jde o pravděpodobnost, ne o příslib.',
    topics: ['vysledky', 'klinika', 'finance'],
  },

  // --- Dárcovství ---------------------------------------------------------
  {
    term: 'Darovaná vajíčka',
    aliases: ['darované oocyty', 'oocytodonace', 'vajíčka od dárkyně'],
    short: 'Vajíčka od jiné ženy, která se oplodní v laboratoři a vzniklé embryo se přenese vám.',
    long: 'Bývá zvažováno při velmi nízké ovariální rezervě, po opakovaně neúspěšných cyklech s vlastními vajíčky, u předčasného ovariálního selhání nebo z genetické indikace. Dárkyně procházejí vyšetřením a dárcovství je v Česku ze zákona anonymní a bezúplatné, hrazena je jen náhrada výdajů. Rozhodnutí je hlavně emoční, ne pouze medicínské, a zaslouží si čas i podporu. Dítě z darovaného vajíčka je dítě, které jste odnosila a porodila.',
    topics: ['darcovstvi', 'psychika'],
  },
  {
    term: 'Darované spermie',
    aliases: ['spermie od dárce', 'dárcovské spermie'],
    short: 'Zamrazený a vyšetřený vzorek od dárce, používaný při inseminaci i při IVF.',
    long: 'Používají se při azoospermii, při závažném genetickém nálezu, u žen bez partnera a u párů žen. Vzorek prochází karanténou a dárce vyšetřením podle platných pravidel. Dárcovství je v Česku anonymní a bezúplatné. Otázka, jestli a jak o původu mluvit s dítětem, patří k tématům, která je lepší otevřít dřív než později.',
    topics: ['darcovstvi', 'partner', 'psychika'],
  },
  {
    term: 'Darované embryo',
    aliases: ['embryodonace'],
    short: 'Embryo darované jiným párem nebo vzniklé z darovaných vajíček a darovaných spermií.',
    long: 'Přichází v úvahu, když nelze použít vlastní vajíčka ani spermie, nebo po opakovaných neúspěších. Právní a etické podmínky jsou přísnější a liší se podle pracoviště i podle země, včetně pravidel pro souhlas dárců. Dítě nebude geneticky vaše ani partnerovo, což je téma na samostatný rozhovor, klidně i s psychologem. Konkrétní možnosti vám vysvětlí vaše klinika.',
    topics: ['darcovstvi', 'psychika', 'vztah'],
  },
  {
    term: 'Anonymita dárcovství',
    short: 'Pravidlo, podle kterého se dárce a příjemkyně v Česku navzájem nedozvědí totožnost.',
    long: 'Klinika údaje o dárci zná a uchovává je, příjemkyni ale sděluje jen omezené informace, obvykle základní tělesné znaky a krevní skupinu. Pravidla se mezi zeměmi liší a v některých státech mají děti po dosažení dospělosti právo znát svůj původ. Dostupnost domácích testů DNA navíc mění to, co lze do budoucna zaručit. Aktuální podmínky si vždy ověřte na své klinice.',
    topics: ['darcovstvi', 'klinika'],
  },
]

export const pack: ContentPack = { items: [], glossary }
